// Africa — World Bucket List data (auto-generated, hand-tuned facts)
window.WBL_AFRICA = [
  {
    id: "cairo-giza-great-pyramid",
    name: "Cairo & Giza — the Great Pyramid",
    region: "Africa",
    country: "Egypt",
    type: "Wonder",
    weekends: 1,
    costUSD: 900,
    lat: 29.98,
    lng: 31.13,
    blurb: "The last standing ancient wonder rises from the desert at the edge of a roaring megacity.",
    wiki: "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza",
    splurge: false,
    badge: "ancient",
    eat: "Koshari — lentils, rice, macaroni and chickpeas under tangy tomato sauce and fried onions",
    tip: "Agree the full price and currency before any camel or horse ride, and pay only at the end, not midway.",
    dont: "Do not photograph military, police or bridges in Cairo — plain-clothes officers will stop you and it is genuinely illegal.",
    bestTime: "October to April, when the Saharan heat eases and mornings at the plateau are cool.",
    phrase: "Shukran (shook-ran) — thank you",
    pacing: "2-3 days",
    headsup: "Carry a wad of small Egyptian pound notes; tipping (baksheesh) is expected for almost every small service and ATMs at the site are unreliable."
  },
  {
    id: "luxor-karnak-valley-kings",
    name: "Luxor — Karnak & Valley of the Kings",
    region: "Africa",
    country: "Egypt",
    type: "Wonder",
    weekends: 1,
    costUSD: 900,
    lat: 25.70,
    lng: 32.64,
    blurb: "An open-air museum of pharaohs, where painted tombs still blaze with colour after three millennia.",
    wiki: "https://en.wikipedia.org/wiki/Karnak",
    splurge: false,
    badge: null,
    eat: "Hamam mahshi — pigeon stuffed with spiced freekeh, a Nile-valley specialty",
    tip: "Buy the photography ticket if you want tomb interior shots — guards enforce the no-camera rule strictly inside the Valley.",
    dont: "Do not touch the tomb wall paintings or lean on them — skin oils accelerate the fading that conservators fight daily.",
    bestTime: "November to February; the West Bank tombs become furnace-hot from spring onward.",
    phrase: "Sabah el-kheir (sa-bah el-kheir) — good morning",
    pacing: "2-3 days",
    headsup: "Cross to the West Bank tombs at opening (around 6am) before the cruise-ship crowds and the heat arrive; bring exact cash for the separate Tutankhamun and Seti I tickets."
  },
  {
    id: "abu-simbel-aswan",
    name: "Abu Simbel & Aswan",
    region: "Africa",
    country: "Egypt",
    type: "Wonder",
    weekends: 1,
    costUSD: 900,
    lat: 22.34,
    lng: 31.63,
    blurb: "Four colossal Ramesses guard a temple that engineers sliced apart and lifted above a rising lake.",
    wiki: "https://en.wikipedia.org/wiki/Abu_Simbel",
    splurge: false,
    badge: null,
    eat: "Aswan-style grilled Nile perch with dukkah, eaten riverside on a Nubian terrace",
    tip: "Aim for the early-morning arrival when the rising sun lights the temple facade most dramatically.",
    dont: "Do not haggle aggressively in Nubian villages as you would in Cairo bazaars — hospitality here is gentler and hard bargaining reads as rude.",
    bestTime: "October to February; also late February or October for the biannual sun-alignment on the inner sanctuary.",
    phrase: "Tislam (tis-lam) — thanks / bless you, a warm Nubian reply",
    pacing: "1-2 days",
    headsup: "Abu Simbel is a 3-hour desert drive from Aswan, often in an organised convoy with fixed departure times; book transport the night before."
  },
  {
    id: "marrakech-atlas-sahara-camel",
    name: "Marrakech, the Atlas & Sahara camel trek",
    region: "Africa",
    country: "Morocco",
    type: "Experience",
    weekends: 1,
    costUSD: 900,
    lat: 31.63,
    lng: -7.99,
    blurb: "Lose yourself in a maze of souks, then ride camels into dunes that glow rose at dusk.",
    wiki: "https://en.wikipedia.org/wiki/Marrakesh",
    splurge: false,
    badge: null,
    eat: "Tanjia marrakchia — slow-cooked lamb sealed in a clay urn and buried in hammam embers",
    tip: "In Jemaa el-Fnaa, snake charmers and water sellers expect a few dirhams the instant you raise a camera.",
    dont: "Do not enter a mosque or step into prayer halls — non-Muslims are not permitted inside most Moroccan mosques.",
    bestTime: "March to May or September to November; the desert is brutally hot in midsummer.",
    phrase: "Shukran bzzaf (shook-ran b-zaf) — thank you very much",
    pacing: "5-7 days with the desert loop",
    headsup: "The desert trek to Merzouga is a long two-day drive each way over the Atlas; \"guides\" who latch onto you in the medina will demand payment, so decline firmly from the start."
  },
  {
    id: "chefchaouen-fez",
    name: "Chefchaouen & Fez",
    region: "Africa",
    country: "Morocco",
    type: "Town",
    weekends: 1,
    costUSD: 900,
    lat: 35.17,
    lng: -5.27,
    blurb: "A mountain town washed entirely in blue, paired with the world's most labyrinthine living medina.",
    wiki: "https://en.wikipedia.org/wiki/Chefchaouen",
    splurge: false,
    badge: null,
    eat: "Bissara — a velvety split-pea soup drizzled with olive oil, the Rif region's breakfast",
    tip: "Carry sprigs of mint to sniff at the Fez tanneries — the leather-dye stench is overwhelming without it.",
    dont: "Do not photograph local women in Chefchaouen without asking — residents tire of being treated as blue-wall backdrops.",
    bestTime: "April to June; spring keeps the Rif mountains green and the medinas comfortable.",
    phrase: "La shukran (la shook-ran) — no thank you, for declining persistent sellers",
    pacing: "3-4 days",
    headsup: "Fez el-Bali has thousands of unmarked alleys and no cars; download offline maps, as your phone GPS drifts badly between the tall walls."
  },
  {
    id: "cape-town-table-mountain",
    name: "Cape Town & Table Mountain",
    region: "Africa",
    country: "South Africa",
    type: "City",
    weekends: 1,
    costUSD: 900,
    lat: -33.92,
    lng: 18.42,
    blurb: "A flat-topped mountain drops straight into two oceans beside vineyards and penguin-strewn beaches.",
    wiki: "https://en.wikipedia.org/wiki/Table_Mountain",
    splurge: false,
    badge: null,
    eat: "Cape Malay bobotie — spiced minced meat baked under a golden egg-and-milk custard",
    tip: "Check the cableway's weather webcam before heading up; the \"tablecloth\" cloud shuts it without warning.",
    dont: "Do not walk isolated trails or beaches alone at dusk — opportunistic muggings happen, so go in groups and stash valuables.",
    bestTime: "November to March for summer sun; the southeaster wind is strongest December-January.",
    phrase: "Howzit — a casual South African \"hello, how are you\"",
    pacing: "4-5 days",
    headsup: "Hire a car: public transport is sparse and the best spots (Cape Point, the winelands, Boulders penguins) are scattered far apart."
  },
  {
    id: "victoria-falls",
    name: "Victoria Falls",
    region: "Africa",
    country: "Zambia",
    type: "Natural",
    weekends: 1,
    costUSD: 900,
    lat: -17.92,
    lng: 25.86,
    blurb: "A mile-wide curtain of the Zambezi thunders into a chasm, throwing spray you can see for miles.",
    wiki: "https://en.wikipedia.org/wiki/Victoria_Falls",
    splurge: false,
    badge: "natural7",
    eat: "Sadza with grilled bream — stiff maize porridge eaten by hand with fresh Zambezi fish",
    tip: "Bring a waterproof jacket and a dry-bag in high-water season; the spray soaks you within minutes on the bridge paths.",
    dont: "Do not change money with the touts at the border or bridge — the rates are scams and the notes are sometimes fake.",
    bestTime: "May to July for full flow with visibility; September-October for swimming Devil's Pool at low water.",
    phrase: "Mwabuka buti (mwa-boo-ka boo-tee) — good morning in Tonga",
    pacing: "2-3 days",
    headsup: "The falls span the Zambia-Zimbabwe border; a KAZA UNIVISA lets you see both sides and cross freely, so buy that rather than a single-country visa."
  },
  {
    id: "zanzibar",
    name: "Zanzibar",
    region: "Africa",
    country: "Tanzania",
    type: "Island",
    weekends: 1,
    costUSD: 900,
    lat: -6.16,
    lng: 39.20,
    blurb: "Spice-scented Stone Town alleys open onto turquoise shallows and dhows under impossibly white sails.",
    wiki: "https://en.wikipedia.org/wiki/Zanzibar",
    splurge: false,
    badge: null,
    eat: "Zanzibar pizza — a stuffed, folded street crepe of minced meat, egg and mayo, fried at Forodhani night market",
    tip: "Time east-coast beach swims to the tide tables; at low tide the water retreats hundreds of metres past the reef.",
    dont: "Do not wear swimwear or skimpy clothing in Stone Town and villages — Zanzibar is conservative and Muslim, so cover shoulders and knees away from the beach.",
    bestTime: "June to October; the dry season avoids the long March-May rains.",
    phrase: "Jambo (jam-bo) — hello",
    pacing: "4-6 days",
    headsup: "Zanzibar charges its own tourist arrival fee and requires mandatory travel insurance on entry separate from mainland Tanzania, so budget and arrange it in advance."
  },
  {
    id: "lalibela",
    name: "Lalibela",
    region: "Africa",
    country: "Ethiopia",
    type: "Wonder",
    weekends: 1,
    costUSD: 900,
    lat: 12.03,
    lng: 39.04,
    blurb: "Eleven churches carved downward into living rock, still alive with chanting white-robed pilgrims.",
    wiki: "https://en.wikipedia.org/wiki/Lalibela",
    splurge: false,
    badge: null,
    eat: "Injera with doro wat — spongy sourdough flatbread torn to scoop fiery chicken-and-egg stew",
    tip: "Hire an official church guide at the ticket office; they unlock the inner sanctuaries and explain the priests' rituals.",
    dont: "Do not enter the rock churches with shoes on — remove them at each threshold as worshippers do.",
    bestTime: "October to March dry season; for spectacle, the Genna (Ethiopian Christmas) pilgrimage in early January.",
    phrase: "Ameseginalehu (a-me-seg-i-na-le-hu) — thank you in Amharic",
    pacing: "2-3 days",
    headsup: "Ethiopia follows its own calendar and a 12-hour clock; confirm whether opening and flight times are \"Ethiopian\" or \"European\" to avoid missing them."
  },
  {
    id: "garden-route-south-africa",
    name: "Garden Route, South Africa",
    region: "Africa",
    country: "South Africa",
    type: "RoadTrip",
    weekends: 2,
    costUSD: 1800,
    lat: -34.05,
    lng: 23.37,
    blurb: "A coastal ribbon of forests, lagoons and ostrich farms strung between cliffs and the Indian Ocean.",
    wiki: "https://en.wikipedia.org/wiki/Garden_Route",
    splurge: false,
    badge: null,
    eat: "Knysna oysters — plump and briny, slurped fresh from the lagoon that grows them",
    tip: "Fill the tank in every town; stretches between fuel stops on the N2 are long and rural.",
    dont: "Do not speed past the roaming \"R\" speed-trap zones near small towns — local traffic police fine foreign rental drivers heavily.",
    bestTime: "October to April; whale-watching off Hermanus and Plettenberg peaks September-November.",
    phrase: "Lekker — Afrikaans slang for great, tasty, or awesome",
    pacing: "7-10 days",
    headsup: "South Africa drives on the left; if you carry a non-English licence (like an Italian one) bring an International Driving Permit or rental desks may refuse you."
  },
  {
    id: "kruger-big-five-safari",
    name: "Kruger — Big Five safari",
    region: "Africa",
    country: "South Africa",
    type: "Experience",
    weekends: 2,
    costUSD: 3300,
    lat: -24.01,
    lng: 31.49,
    blurb: "Self-drive among lions, elephants and rhino across savanna the size of a small country.",
    wiki: "https://en.wikipedia.org/wiki/Kruger_National_Park",
    splurge: true,
    badge: null,
    eat: "Boerewors roll — coiled farmer's sausage grilled at a braai and stuffed into a soft roll",
    tip: "Book a sunrise guided drive; gates open before dawn when predators are most active and the light is golden.",
    dont: "Do not get out of your vehicle outside designated camps or rest stops — it is lethal and strictly forbidden.",
    bestTime: "May to September dry season, when thin bush and shrinking waterholes concentrate game.",
    phrase: "Sawubona (sa-woo-bo-na) — hello in Zulu",
    pacing: "4-7 days",
    headsup: "Camp gate times are enforced to the minute and you are fined for arriving late; plan drives to return well before closing."
  },
  {
    id: "serengeti-ngorongoro-migration",
    name: "Serengeti & Ngorongoro — the Great Migration",
    region: "Africa",
    country: "Tanzania",
    type: "Experience",
    weekends: 2,
    costUSD: 4160,
    lat: -2.33,
    lng: 34.83,
    blurb: "A million wildebeest pour across endless plains while big cats shadow the herds and crocodiles wait.",
    wiki: "https://en.wikipedia.org/wiki/Serengeti",
    splurge: true,
    badge: null,
    eat: "Nyama choma — charcoal-grilled goat or beef eaten with kachumbari tomato-onion salad",
    tip: "Match your dates to where the herds are: calving in the south around February, the river crossings in the north mid-year.",
    dont: "Do not pressure your driver to go off-track for a closer photo — it is banned, scars the grassland, and risks a steep fine.",
    bestTime: "Late June to October for Mara River crossings; January-March for the southern calving.",
    phrase: "Asante sana (a-san-te sa-na) — thank you very much in Swahili",
    pacing: "6-9 days",
    headsup: "Park fees and the Ngorongoro Crater service fee are steep and often payable separately; confirm exactly what your operator's quote includes before booking."
  },
  {
    id: "maasai-mara-safari",
    name: "Maasai Mara safari",
    region: "Africa",
    country: "Kenya",
    type: "Experience",
    weekends: 2,
    costUSD: 3300,
    lat: -1.49,
    lng: 35.14,
    blurb: "Golden grasslands packed with lion prides and cheetahs, where the migration spills across the Mara River.",
    wiki: "https://en.wikipedia.org/wiki/Maasai_Mara",
    splurge: true,
    badge: null,
    eat: "Ugali with sukuma wiki — firm maize cake paired with sauteed collard greens",
    tip: "Stay in a conservancy bordering the reserve for off-road night drives and far fewer minivans at sightings.",
    dont: "Do not photograph Maasai people or their villages without agreeing a fee first — it is expected and snapping for free causes offence.",
    bestTime: "July to October for the migration and river crossings; calving and lush scenery January-February.",
    phrase: "Supa (soo-pa) — hello in Maa",
    pacing: "4-6 days",
    headsup: "Many lodges and the reserve gate are cash-friendly but card-shy; carry US dollars in clean, post-2013 notes, which Kenya widely accepts."
  },
  {
    id: "okavango-delta-chobe",
    name: "Okavango Delta & Chobe",
    region: "Africa",
    country: "Botswana",
    type: "Experience",
    weekends: 2,
    costUSD: 4300,
    lat: -19.28,
    lng: 22.83,
    blurb: "Glide a dugout canoe through reed channels into a flooded Eden teeming with elephants and lions.",
    wiki: "https://en.wikipedia.org/wiki/Okavango_Delta",
    splurge: true,
    badge: null,
    eat: "Seswaa — slow-pounded salted beef served over pap, Botswana's national feast dish",
    tip: "Take a mokoro (dugout canoe) at dawn or dusk; the silent gliding gets you astonishingly close to wildlife.",
    dont: "Do not trail your hand in the water from the mokoro — hippos and crocodiles make the channels genuinely dangerous.",
    bestTime: "June to September, when the floodwaters peak and dry land draws game to the channels.",
    phrase: "Dumela (doo-meh-la) — hello in Setswana",
    pacing: "5-8 days",
    headsup: "Botswana runs high-cost, low-volume tourism; delta camps are fly-in only via tiny bush planes with strict ~15kg soft-bag luggage limits."
  },
  {
    id: "namibia-sossusvlei-dunes",
    name: "Namibia — Sossusvlei dunes",
    region: "Africa",
    country: "Namibia",
    type: "Natural",
    weekends: 2,
    costUSD: 1800,
    lat: -24.73,
    lng: 15.35,
    blurb: "Climb the world's tallest rust-red dunes to white clay pans studded with blackened thousand-year-old trees.",
    wiki: "https://en.wikipedia.org/wiki/Sossusvlei",
    splurge: false,
    badge: null,
    eat: "Kapana — sizzling street-grilled beef strips dipped in fiery chilli, a Namibian market staple",
    tip: "Enter the park gate at sunrise to climb Big Daddy or Dune 45 before the sand becomes scorching underfoot.",
    dont: "Do not walk on the cracked white floor of Deadvlei beyond the marked areas — footprints scar the fragile clay for years.",
    bestTime: "May to September; cooler days make dune climbing bearable and skies stay clear.",
    phrase: "Aaitsama — a friendly Damara/Nama greeting; or simply \"Hallo\" in Afrikaans",
    pacing: "7-10 days for the wider country",
    headsup: "Distances are vast on gravel roads with almost no fuel or signal; rent a 4x4, carry a spare tyre and water, and never drive at night for the wildlife."
  },
  {
    id: "kilimanjaro-climb",
    name: "Kilimanjaro climb",
    region: "Africa",
    country: "Tanzania",
    type: "Trek",
    weekends: 3,
    costUSD: 5700,
    lat: -3.07,
    lng: 37.35,
    blurb: "Walk from rainforest to glaciers, summiting Africa's rooftop for a sunrise above the clouds.",
    wiki: "https://en.wikipedia.org/wiki/Mount_Kilimanjaro",
    splurge: true,
    badge: null,
    eat: "Mishkaki — marinated beef skewers grilled roadside in Moshi, the climbers' base town",
    tip: "Choose a longer route like Lemosho or Machame over the rushed Marangu; the extra days dramatically raise your summit odds.",
    dont: "Do not skimp on tipping your guides and porters at the end — the customary pooled tip is a major part of their livelihood.",
    bestTime: "January to mid-March or June to October dry windows; avoid the heavy April-May rains.",
    phrase: "Pole pole (po-le po-le) — slowly, slowly, the mantra for altitude pacing",
    pacing: "6-9 days on the mountain",
    headsup: "Altitude sickness is the real danger, not the cold; ascend slowly, consider Diamox, and know that porter welfare rules (KPAP) mark the ethical operators."
  },
  {
    id: "gorilla-trekking-bwindi-volcanoes",
    name: "Gorilla trekking — Bwindi / Volcanoes",
    region: "Africa",
    country: "Uganda",
    type: "Experience",
    weekends: 2,
    costUSD: 3600,
    lat: -1.06,
    lng: 29.62,
    blurb: "Scramble through dripping cloud forest to sit metres from a silverback and his foraging family.",
    wiki: "https://en.wikipedia.org/wiki/Bwindi_Impenetrable_National_Park",
    splurge: true,
    badge: null,
    eat: "Rolex — a chapati rolled around fried eggs and vegetables, Uganda's beloved street snack",
    tip: "Hire a porter at the trailhead; they steady you on muddy slopes and the small fee directly supports local communities.",
    dont: "Do not visit the gorillas if you have a cold or flu — they share our diseases, and rangers can rightly turn you away.",
    bestTime: "June to September or December to February dry seasons, when forest trails are less of a mudbath.",
    phrase: "Webale (weh-ba-leh) — thank you in Luganda",
    pacing: "3-4 days",
    headsup: "Permits are strictly limited, costly, and sell out months ahead; you must buy one in advance and keep at least 7 metres from the gorillas."
  },
];
