// Asia — World Bucket List data (auto-generated, hand-tuned facts)
window.WBL_ASIA = [
  {
    id: "petra-wadi-rum-dead-sea",
    name: "Petra, Wadi Rum & the Dead Sea",
    region: "Asia",
    country: "Jordan",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: 30.33,
    lng: 35.44,
    blurb: "A rose-red city carved into cliffs, then float in a sea you cannot sink in.",
    wiki: "https://en.wikipedia.org/wiki/Petra",
    splurge: false,
    badge: "new7",
    eat: "Mansaf — lamb cooked in fermented dried-yogurt jameed over rice, Jordan's national dish",
    tip: "Buy the Jordan Pass online before you fly; it bundles the visa fee and Petra entry and saves real money.",
    dont: "Do not ride the camels and donkeys pushed at Petra's steps; many are overworked, and animal-welfare groups urge visitors to walk.",
    bestTime: "March-May or September-November, when the canyon isn't baking or freezing.",
    phrase: "Shukran (shook-ran) — thank you",
    pacing: "4-5 days",
    headsup: "Shave before the Dead Sea, skip wet-shaving days entirely; salt water in any cut or your eyes is searing, and never dunk your head."
  },
  {
    id: "jerusalem-old-city",
    name: "Jerusalem",
    region: "Asia",
    country: "Israel",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 31.78,
    lng: 35.22,
    blurb: "Three faiths layered on one walled hill, where prayer and politics share every stone.",
    wiki: "https://en.wikipedia.org/wiki/Jerusalem",
    splurge: false,
    badge: null,
    eat: "Sabich — pita stuffed with fried eggplant, hard egg, hummus and amba mango sauce, a Jerusalem street staple",
    tip: "From Friday sundown to Saturday night the city shuts for Shabbat; buses stop and most Jewish-run places close, so stock up Friday morning.",
    dont: "Do not visit the Western Wall or holy sites in shorts or bare shoulders; modest dress is expected and at the Wall men and women pray separately.",
    bestTime: "March-May, before the summer heat and crowds of pilgrims.",
    phrase: "Toda (toh-dah) — thank you (Hebrew); Shukran in Arabic",
    pacing: "3-4 days",
    headsup: "Bring your passport everywhere; security checks at the Old City gates and holy sites are routine, and the Temple Mount has limited, faith-restricted visiting hours."
  },
  {
    id: "dubai-abu-dhabi",
    name: "Dubai & Abu Dhabi",
    region: "Asia",
    country: "United Arab Emirates",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 25.20,
    lng: 55.27,
    blurb: "The world's tallest tower, indoor ski slopes and desert dunes all before dinner.",
    wiki: "https://en.wikipedia.org/wiki/Dubai",
    splurge: false,
    badge: null,
    eat: "Camel milk karak chai — strong, sweet cardamom tea, the unofficial drink of every Emirati roadside stop",
    tip: "Use the Dubai Metro and a topped-up Nol card; it is spotless, cheap and skips the brutal traffic, with a women-and-children-only carriage at each train's front.",
    dont: "Do not show public affection beyond hand-holding or swear and make rude gestures; these are genuinely fined or jailed under UAE decency laws.",
    bestTime: "November-March; summer hits dangerous mid-40s Celsius heat.",
    phrase: "Shukran (shook-ran) — thank you",
    pacing: "3-4 days",
    headsup: "Alcohol is sold only in licensed hotels and bars, never on the street, and being drunk in public is an offence; during Ramadan, avoid eating or drinking in daylight outdoors."
  },
  {
    id: "persepolis",
    name: "Persepolis",
    region: "Asia",
    country: "Iran",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: 29.93,
    lng: 52.89,
    blurb: "Darius the Great's ceremonial capital, where stone armies still march up the Apadana stairs.",
    wiki: "https://en.wikipedia.org/wiki/Persepolis",
    splurge: false,
    badge: null,
    eat: "Fesenjan — duck or chicken stewed in pomegranate molasses and ground walnuts, a Persian classic from nearby Shiraz",
    tip: "Carry plenty of cash in rials; foreign bank and credit cards do not work in Iran, so you exchange and budget for the whole trip up front.",
    dont: "Do not touch or photograph local women without consent, and women travellers must wear a headscarf in public; rules are enforced.",
    bestTime: "April-May or October, avoiding the searing Fars summer.",
    phrase: "Merci / Mamnoon (mam-noon) — thank you",
    pacing: "Half a day at the site, 2-3 days with Shiraz",
    headsup: "Most foreigners need a guide or pre-arranged tour and a visa secured in advance; shade and water are scarce on the exposed terrace, so go early morning."
  },
  {
    id: "golden-triangle-taj-mahal",
    name: "Golden Triangle — Delhi, Agra (Taj Mahal) & Jaipur",
    region: "Asia",
    country: "India",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: 27.17,
    lng: 78.04,
    blurb: "A marble mausoleum that glows pink at dawn, anchoring a triangle of forts and bazaars.",
    wiki: "https://en.wikipedia.org/wiki/Taj_Mahal",
    splurge: false,
    badge: "new7",
    eat: "Dal Baati Churma — Rajasthani baked wheat balls with lentils and sweet crumble, the soul food of Jaipur",
    tip: "Book Taj Mahal tickets online and arrive for sunrise opening; the light is sublime, crowds thinner, and Fridays it is closed for prayers.",
    dont: "Do not bring food, tripods or large bags into the Taj; only small bottles and cameras are allowed, and you must remove shoes or wear the provided covers near the tomb.",
    bestTime: "October-March; the pre-monsoon months scorch and the haze hides the marble.",
    phrase: "Dhanyavaad (dhun-yuh-vaad) — thank you (Hindi)",
    pacing: "5-6 days",
    headsup: "Pre-book a driver for the whole loop and ignore the touts who claim your hotel closed or your monument moved; the fake-tour-guide scam is rampant here."
  },
  {
    id: "mumbai",
    name: "Mumbai",
    region: "Asia",
    country: "India",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 18.96,
    lng: 72.83,
    blurb: "Bollywood dreams, colonial arcades and Asia's biggest laundry, all crashing into the Arabian Sea.",
    wiki: "https://en.wikipedia.org/wiki/Mumbai",
    splurge: false,
    badge: null,
    eat: "Vada pav — a spiced potato fritter in a soft bun with chutneys, the city's beloved street burger",
    tip: "Ride the suburban local trains off-peak to feel the city's pulse, but never during the morning rush unless you enjoy being a sardine.",
    dont: "Do not photograph the Dhobi Ghat laundry workers or Dharavi residents without asking; it turns people's livelihoods into a zoo exhibit.",
    bestTime: "November-February, the dry cool window before the wild June monsoon.",
    phrase: "Aabhari aahe (aa-bhaa-ree aa-hay) — thank you (Marathi)",
    pacing: "3-4 days",
    headsup: "Use the prepaid taxi booth at the airport or the Uber/Ola apps; meter taxis often refuse the meter or take scenic detours with newcomers."
  },
  {
    id: "varanasi",
    name: "Varanasi",
    region: "Asia",
    country: "India",
    type: "Experience",
    weekends: 1,
    costUSD: 750,
    lat: 25.31,
    lng: 83.01,
    blurb: "Pyres, prayer and pilgrims meet at the Ganges at dawn in Hinduism's holiest city.",
    wiki: "https://en.wikipedia.org/wiki/Varanasi",
    splurge: false,
    badge: null,
    eat: "Banarasi paan — betel leaf folded with rose, fennel and gulkand, chewed as a sweet ritual after meals",
    tip: "Hire a rowboat for the sunrise float past the ghats; it is the only calm vantage to watch the city wake and bathe in the river.",
    dont: "Never photograph the cremations at Manikarnika Ghat; it is a sacred funeral, not a spectacle, and locals find it deeply disrespectful.",
    bestTime: "October-March, especially for the Dev Deepawali festival of lamps in November.",
    phrase: "Dhanyavaad (dhun-yuh-vaad) — thank you (Hindi)",
    pacing: "2-3 days",
    headsup: "Beware the 'free' guides at the burning ghats who demand large 'wood donations' afterwards; the lanes are a maze, so note landmarks or use offline maps."
  },
  {
    id: "sigiriya-sri-lanka",
    name: "Sri Lanka — Sigiriya",
    region: "Asia",
    country: "Sri Lanka",
    type: "Town",
    weekends: 1,
    costUSD: 750,
    lat: 7.96,
    lng: 80.76,
    blurb: "Climb a sheer rock fortress past frescoed maidens to a king's sky palace.",
    wiki: "https://en.wikipedia.org/wiki/Sigiriya",
    splurge: false,
    badge: null,
    eat: "Kottu roti — chopped flatbread stir-fried with vegetables, egg and curry, hammered out to a rhythmic clang on a hot griddle",
    tip: "Start the rock climb right at the 7am opening to beat the heat, the hornets and the tour buses; bring water for the 1,200 steps.",
    dont: "Do not turn your back on a Buddha statue for a selfie or pose touching it; it is illegal here and tourists have been deported for it.",
    bestTime: "January-March, the dry season for the Cultural Triangle.",
    phrase: "Istuti (iss-too-tee) — thank you (Sinhala)",
    pacing: "2-3 days around the Cultural Triangle",
    headsup: "Wasps nest on the rock and react to noise; signs ask for quiet on the upper terraces, and if a swarm stirs, freeze rather than swat or run."
  },
  {
    id: "maldives-atolls",
    name: "Maldives atolls",
    region: "Asia",
    country: "Maldives",
    type: "Island",
    weekends: 1,
    costUSD: 750,
    lat: 3.20,
    lng: 73.22,
    blurb: "Overwater bungalows over glass-clear lagoons, with reef sharks gliding beneath your deck.",
    wiki: "https://en.wikipedia.org/wiki/Maldives",
    splurge: false,
    badge: null,
    eat: "Mas huni — shredded smoked tuna with coconut, onion and chilli, scooped up with flaky roshi flatbread at breakfast",
    tip: "Choose between a one-resort-per-island splurge or a far cheaper local guesthouse on an inhabited island; the latter lets you actually meet Maldivians.",
    dont: "Do not sunbathe in a bikini on local (non-resort) islands; these are Muslim communities, and bikinis are only fine on resort islands or marked 'bikini beaches'.",
    bestTime: "November-April, the dry northeast-monsoon season with calm, clear water.",
    phrase: "Shukuriyaa (shoo-koo-ree-yaa) — thank you (Dhivehi)",
    pacing: "5-7 days",
    headsup: "Alcohol is banned outside resorts, and seaplane transfers run only in daylight; arrive on a morning flight or you may overnight in Male before reaching your island."
  },
  {
    id: "bangkok-ayutthaya",
    name: "Bangkok & Ayutthaya",
    region: "Asia",
    country: "Thailand",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 13.75,
    lng: 100.49,
    blurb: "Glittering temples and canal markets give way to the ruined Buddha heads of an old capital.",
    wiki: "https://en.wikipedia.org/wiki/Bangkok",
    splurge: false,
    badge: null,
    eat: "Boat noodles — small, intense bowls of dark pork or beef broth, traditionally sold from canal boats",
    tip: "Beat traffic with the Chao Phraya river express boats and the BTS Skytrain; the orange-flag boat is the cheap, fast way to reach the temples.",
    dont: "Never disrespect images of the King or step on Thai money to stop it rolling away; the royal portrait is on it, and lese-majeste laws are strict.",
    bestTime: "November-February, the cool dry season before the April furnace.",
    phrase: "Khop khun krap/ka (kop-koon krap for men, ka for women) — thank you",
    pacing: "4-5 days with Ayutthaya day trip",
    headsup: "Ignore tuk-tuk drivers offering a '20-baht grand tour'; it is a gem-shop and tailor scam, and so is anyone claiming the Grand Palace is 'closed today'."
  },
  {
    id: "thai-islands-phuket",
    name: "Thai islands & Phuket",
    region: "Asia",
    country: "Thailand",
    type: "Island",
    weekends: 1,
    costUSD: 750,
    lat: 7.89,
    lng: 98.40,
    blurb: "Limestone karsts erupt from turquoise bays you reach by longtail boat and kayak.",
    wiki: "https://en.wikipedia.org/wiki/Phuket_Province",
    splurge: false,
    badge: null,
    eat: "Massaman curry — a mild, peanutty Muslim-influenced curry with potato and tender beef, a southern Thai specialty",
    tip: "Rent the right boat day: the Phi Phi and James Bond island tours fill by mid-morning, so book a small-group dawn departure to swim before the armada arrives.",
    dont: "Do not touch or step on the coral or feed the fish on snorkel trips; reefs here are stressed and protected, with fines in the marine parks.",
    bestTime: "November-April; the May-October monsoon brings rough seas and red-flag beaches.",
    phrase: "Sawasdee krap/ka (sa-wat-dee) — hello",
    pacing: "5-7 days island-hopping",
    headsup: "Beware rented jet-ski and scooter 'damage' scams where minor scratches trigger huge fines; photograph every vehicle before you take it and keep your passport."
  },
  {
    id: "angkor-wat",
    name: "Angkor Wat",
    region: "Asia",
    country: "Cambodia",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: 13.41,
    lng: 103.87,
    blurb: "The world's largest temple, with jungle-strangled towers and faces smiling out of the stone.",
    wiki: "https://en.wikipedia.org/wiki/Angkor_Wat",
    splurge: false,
    badge: null,
    eat: "Fish amok — coconut-curry fish custard steamed in a banana leaf, Cambodia's signature dish",
    tip: "Buy the multi-day Angkor pass at the official ticket office (not from hawkers) and hire a tuk-tuk driver for the day to loop the scattered temples efficiently.",
    dont: "Do not climb on the temples or pose disrespectfully (no bare shoulders or knees at Angkor Wat's upper level); it is an active sacred site, not a playground.",
    bestTime: "November-February, the cool dry season; come before sunrise for the reflection over the moat.",
    phrase: "Arkun (or-kun) — thank you (Khmer)",
    pacing: "3-4 days for the wider Angkor complex",
    headsup: "Bring small US dollars; Cambodia runs largely on USD, prices are quoted in it, and change under a dollar comes back in riel."
  },
  {
    id: "ha-long-bay-hanoi",
    name: "Ha Long Bay & Hanoi",
    region: "Asia",
    country: "Vietnam",
    type: "Natural",
    weekends: 1,
    costUSD: 750,
    lat: 20.91,
    lng: 107.18,
    blurb: "Thousands of jungle-topped limestone islands drift past your junk on emerald water.",
    wiki: "https://en.wikipedia.org/wiki/H%E1%BA%A1_Long_Bay",
    splurge: false,
    badge: null,
    eat: "Bun cha — grilled pork patties in a tangy fish-sauce broth with herbs and noodles, a Hanoi lunchtime ritual",
    tip: "Pick a reputable overnight cruise into quieter Lan Ha Bay or Bai Tu Long to escape the day-tripper crush around the main bay.",
    dont: "In Hanoi do not cross the chaotic streets by darting or stopping; walk slowly and steadily so the river of scooters can flow around you.",
    bestTime: "October-April for cooler, clearer days; summer brings haze and typhoon risk on the bay.",
    phrase: "Cam on (kahm uhn) — thank you (Vietnamese)",
    pacing: "4-5 days with a Hanoi base",
    headsup: "Cruise quality varies wildly for the same price; read recent reviews, and note sailings get cancelled for storms with little notice, so keep your schedule flexible."
  },
  {
    id: "hoi-an-hue",
    name: "Hoi An & Hue",
    region: "Asia",
    country: "Vietnam",
    type: "Town",
    weekends: 1,
    costUSD: 750,
    lat: 15.88,
    lng: 108.33,
    blurb: "A lantern-lit trading port and a moated imperial citadel strung along central Vietnam's coast.",
    wiki: "https://en.wikipedia.org/wiki/H%E1%BB%99i_An",
    splurge: false,
    badge: null,
    eat: "Cao lau — chewy noodles with pork, greens and crackers, made only in Hoi An with water from its ancient Ba Le well",
    tip: "Order custom clothes from a Hoi An tailor on day one so there is time for two fittings; the town built its name on bespoke suits and dresses.",
    dont: "Do not haggle aggressively or mockingly in the old town's quiet shops; firm but friendly bargaining is fine, sneering is not.",
    bestTime: "February-April, dry and warm before the October-November flooding season.",
    phrase: "Xin chao (sin chow) — hello (Vietnamese)",
    pacing: "3-4 days",
    headsup: "The walking-only old town charges an entry ticket that funds the heritage sites; buy it rather than dodging it, and time a visit for the monthly full-moon lantern night."
  },
  {
    id: "luang-prabang",
    name: "Luang Prabang",
    region: "Asia",
    country: "Laos",
    type: "Town",
    weekends: 1,
    costUSD: 750,
    lat: 19.89,
    lng: 102.13,
    blurb: "Saffron-robed monks pad through a golden riverside town of teak temples and French cafes.",
    wiki: "https://en.wikipedia.org/wiki/Luang_Prabang",
    splurge: false,
    badge: null,
    eat: "Or lam — a smoky Luang Prabang stew of buffalo meat, eggplant and the tongue-tingling sakhan vine pepper",
    tip: "Watch the dawn tak bat alms procession from across the street and in silence; the best experience is to observe respectfully, not to crowd the monks.",
    dont: "Do not buy mass-produced rice from vendors to join the alms-giving for photos; it disrupts a sacred ritual, and tourists shoving cameras in monks' faces is a known problem.",
    bestTime: "November-February, the cool dry season; the Kuang Si waterfalls are bluest then.",
    phrase: "Khop chai (kop jai) — thank you (Lao)",
    pacing: "3-4 days",
    headsup: "The town enforces a curfew and is very low-key by night; ATMs can be unreliable, so carry enough kip, and dress covering shoulders and knees for the temples."
  },
  {
    id: "bali",
    name: "Bali",
    region: "Asia",
    country: "Indonesia",
    type: "Island",
    weekends: 1,
    costUSD: 750,
    lat: -8.41,
    lng: 115.19,
    blurb: "Terraced rice valleys, cliff temples over the surf and offerings on every doorstep.",
    wiki: "https://en.wikipedia.org/wiki/Bali",
    splurge: false,
    badge: null,
    eat: "Babi guling — Balinese spit-roast suckling pig stuffed with turmeric, lemongrass and chilli, served at festive warungs",
    tip: "Step over, never on, the little canang sari flower offerings on the pavement; they are placed fresh daily as gifts to the spirits.",
    dont: "Do not enter temples in revealing clothes or, for women, during menstruation (signs say so); always wear the sarong provided and never climb on sacred statues.",
    bestTime: "April-October, the dry season; the wet months bring daily downpours.",
    phrase: "Terima kasih (te-ree-ma ka-see) — thank you (Indonesian)",
    pacing: "7-10 days",
    headsup: "Traffic is brutal and Uber/Grab is restricted in some tourist zones; hire a private driver for day trips, and carry rupiah cash since many warungs are cash-only."
  },
  {
    id: "borobudur-yogyakarta",
    name: "Borobudur & Yogyakarta",
    region: "Asia",
    country: "Indonesia",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: -7.61,
    lng: 110.20,
    blurb: "The world's largest Buddhist temple rises in stone tiers above the misty Javanese plain.",
    wiki: "https://en.wikipedia.org/wiki/Borobudur",
    splurge: false,
    badge: null,
    eat: "Gudeg — young jackfruit slow-stewed in palm sugar and coconut milk, the sweet signature dish of Yogyakarta",
    tip: "Book the limited upper-level climb slot in advance and wear the provided upakara sandals; numbers on the monument are now capped to protect the stone.",
    dont: "Do not touch or rub the Buddha statues inside the stupas for luck; it damages the volcanic stone, and access is now restricted for that reason.",
    bestTime: "May-September dry season; clear dawn skies give the best view toward the volcanoes.",
    phrase: "Matur nuwun (ma-toor noo-woon) — thank you (Javanese)",
    pacing: "2-3 days with Prambanan",
    headsup: "Sunrise viewing is now usually from a nearby hill or hotel, not the temple itself, and same-day tickets sell out; buy online and combine with the Hindu Prambanan temples."
  },
  {
    id: "bagan",
    name: "Bagan",
    region: "Asia",
    country: "Myanmar",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: 21.17,
    lng: 94.86,
    blurb: "Thousands of brick temples pierce the dawn mist as hot-air balloons drift overhead.",
    wiki: "https://en.wikipedia.org/wiki/Bagan",
    splurge: false,
    badge: null,
    eat: "Mohinga — a lemongrass and catfish rice-noodle soup eaten for breakfast, regarded as Myanmar's national dish",
    tip: "Rent an electric e-bike to roam the dusty temple tracks at your own pace; it is the local way to cover the vast plain between sites.",
    dont: "Do not climb on the temples to watch sunrise; it is now banned after earthquake damage and several deaths, so use the official viewing mounds.",
    bestTime: "November-February, dry and cooler before the searing heat of April.",
    phrase: "Kyay zu tin bar deh (chay-zoo-tin-ba-deh) — thank you (Burmese)",
    pacing: "3 days",
    headsup: "Check current travel advisories before booking; Myanmar's situation is unstable, cards rarely work, so bring pristine US dollars and pay the archaeological-zone fee on arrival."
  },
  {
    id: "singapore",
    name: "Singapore",
    region: "Asia",
    country: "Singapore",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 1.35,
    lng: 103.82,
    blurb: "Supertrees, rooftop pools and hawker feasts pack a spotless tropical city-state.",
    wiki: "https://en.wikipedia.org/wiki/Singapore",
    splurge: false,
    badge: null,
    eat: "Hainanese chicken rice — poached chicken with fragrant ginger-and-garlic rice and chilli sauce, the unofficial national dish",
    tip: "Eat at the hawker centres like Maxwell or Lau Pa Sat, and 'chope' (reserve) your seat with a packet of tissues like the locals before queueing.",
    dont: "Do not eat, drink or chew gum on the MRT or litter anywhere; fines are real and steep, and selling chewing gum is actually banned.",
    bestTime: "February-April is slightly drier; it is hot and humid year-round.",
    phrase: "Lah — an all-purpose Singlish suffix added for emphasis, as in 'OK lah'",
    pacing: "3-4 days",
    headsup: "Jaywalking, vaping and importing e-cigarettes are illegal and fined; alcohol is pricey and a public no-sale window runs from 10:30pm to 7am."
  },
  {
    id: "boracay-palawan",
    name: "Boracay & Palawan",
    region: "Asia",
    country: "Philippines",
    type: "Island",
    weekends: 1,
    costUSD: 750,
    lat: 10.18,
    lng: 118.91,
    blurb: "Powder-white sand on Boracay, then island-hop a lagoon-laced limestone paradise in Palawan.",
    wiki: "https://en.wikipedia.org/wiki/El_Nido,_Palawan",
    splurge: false,
    badge: null,
    eat: "Kinilaw — raw tuna or fish 'cooked' in vinegar and calamansi with ginger and chilli, the Filipino take on ceviche",
    tip: "On Boracay's White Beach there is a strict no-smoking, no-drinking and no-sandcastle rule after a major clean-up; respect the marked zones.",
    dont: "Do not pile onto a single overloaded bangka boat or skip the life vest on island tours; sudden squalls cause real accidents in these waters.",
    bestTime: "December-May dry season; avoid the June-October typhoon and habagat months.",
    phrase: "Salamat (sa-la-mat) — thank you (Filipino)",
    pacing: "6-8 days across both islands",
    headsup: "Getting between Boracay and Palawan means flying via Manila or Cebu and a boat transfer; build in buffer days, as small-plane and ferry delays are common."
  },
  {
    id: "mount-kinabalu",
    name: "Mount Kinabalu",
    region: "Asia",
    country: "Malaysia",
    type: "Trek",
    weekends: 1,
    costUSD: 750,
    lat: 6.08,
    lng: 116.56,
    blurb: "Borneo's granite giant, climbed overnight to catch sunrise above a sea of cloud.",
    wiki: "https://en.wikipedia.org/wiki/Mount_Kinabalu",
    splurge: false,
    badge: null,
    eat: "Hinava — Kadazan-Dusun raw fish cured in lime with ginger, shallots and grated bitter-gourd seed, Sabah's signature dish",
    tip: "Book a Sutera/Mountain Torq climbing permit and Laban Rata hut months ahead; daily climber numbers are strictly capped and sell out fast.",
    dont: "Do not pose nude or disrespect the summit; the mountain is sacred to the Kadazan-Dusun, and a 2015 nude-photo incident caused a genuine national scandal.",
    bestTime: "March-April, the driest, clearest stretch for summit views.",
    phrase: "Terima kasih (te-ree-ma ka-see) — thank you (Malay)",
    pacing: "2 days (overnight at Laban Rata)",
    headsup: "A licensed mountain guide is mandatory and altitude can hit hard near the 4,095m summit; pack warm layers, as the 2am final push to Low's Peak is bitterly cold."
  },
  {
    id: "tokyo-mt-fuji",
    name: "Tokyo & Mt Fuji",
    region: "Asia",
    country: "Japan",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 35.68,
    lng: 139.69,
    blurb: "Neon-soaked megacity electricity, then the perfect snow cone of Fuji on the horizon.",
    wiki: "https://en.wikipedia.org/wiki/Tokyo",
    splurge: false,
    badge: null,
    eat: "Monjayaki — a runny, savoury Tokyo griddle-pancake you cook and scrape off the hotplate yourself, the city's Tsukishima specialty",
    tip: "Get a Suica or PASMO IC card for trains, vending machines and konbini; tap-and-go beats fumbling for paper tickets in Tokyo's vast network.",
    dont: "Do not tip in restaurants or taxis; it confuses or even offends staff here, where good service is simply expected, not bought.",
    bestTime: "March-April for blossoms or October-November for crisp clear Fuji views.",
    phrase: "Arigato gozaimasu (a-ri-ga-toh go-zai-mas) — thank you",
    pacing: "5-7 days with a Fuji day trip",
    headsup: "Carry some cash; many smaller shops, shrines and ramen joints are cash-only despite Tokyo's high-tech image, and to actually climb Fuji you must come in the short July-September season."
  },
  {
    id: "kyoto-osaka-nara",
    name: "Kyoto, Osaka & Nara — cherry blossoms",
    region: "Asia",
    country: "Japan",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 35.01,
    lng: 135.77,
    blurb: "Vermilion torii gates, geisha lanes and bowing deer beneath drifting pink petals.",
    wiki: "https://en.wikipedia.org/wiki/Kyoto",
    splurge: false,
    badge: null,
    eat: "Yudofu — silky simmered tofu in delicate kombu broth, a Kyoto temple-cuisine specialty eaten near Nanzen-ji",
    tip: "Visit Fushimi Inari's torii gates or Arashiyama at dawn before the crowds, and in Osaka's Dotonbori try the local takoyaki octopus balls.",
    dont: "Do not chase, grab or block geiko and maiko for photos in Gion; harassment got parts of the district closed to tourists, so keep a respectful distance.",
    bestTime: "Late March-early April for sakura; book lodging months ahead as it is peak season.",
    phrase: "Ookini (oh-kee-nee) — thank you (Kyoto/Kansai dialect)",
    pacing: "5-6 days across the three cities",
    headsup: "Cherry-blossom timing shifts yearly by a week or two; track the bloom forecast and book early, and in Nara bow back to the deer for a cracker but don't tease them, they nip."
  },
  {
    id: "hiroshima-miyajima",
    name: "Hiroshima & Miyajima",
    region: "Asia",
    country: "Japan",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 34.39,
    lng: 132.45,
    blurb: "A city reborn around its Peace Memorial, beside a torii gate that floats at high tide.",
    wiki: "https://en.wikipedia.org/wiki/Hiroshima",
    splurge: false,
    badge: null,
    eat: "Hiroshima-style okonomiyaki — a layered savoury pancake with noodles, cabbage and egg, cooked in stacks unlike the Osaka kind",
    tip: "Visit the Peace Memorial Park and Museum with quiet respect; many survivors' families still come, and the displays are sobering, so allow unhurried time.",
    dont: "Do not treat the A-Bomb Dome or memorials as a cheerful photo backdrop or fold loud jokes into the moment; it honours over a hundred thousand dead.",
    bestTime: "Spring or autumn; time Miyajima for high tide when the great torii appears to float.",
    phrase: "Arigato gozaimasu (a-ri-ga-toh go-zai-mas) — thank you",
    pacing: "2 days",
    headsup: "Check Miyajima tide tables before you go, as the floating torii sits on mud at low tide, and note a small island visitor tax now applies on arrival."
  },
  {
    id: "beijing-forbidden-city-great-wall",
    name: "Beijing — Forbidden City & Great Wall",
    region: "Asia",
    country: "China",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: 39.92,
    lng: 116.40,
    blurb: "An emperor's 900-room palace, then the dragon's-back Wall snaking over the hills.",
    wiki: "https://en.wikipedia.org/wiki/Great_Wall_of_China",
    splurge: false,
    badge: "new7",
    eat: "Peking duck — lacquered roast duck carved into crisp-skinned slices, wrapped in thin pancakes with scallion and hoisin",
    tip: "Reserve the Forbidden City online days ahead with your passport (daily numbers are capped) and pick a quieter Wall section like Mutianyu over packed Badaling.",
    dont: "Do not assume your usual apps work; Google, WhatsApp and Instagram are blocked, so set up a VPN before arrival and download WeChat and a maps app first.",
    bestTime: "September-October for clear skies and mild temperatures; avoid the smoggy winter.",
    phrase: "Xiexie (shyeh-shyeh) — thank you (Mandarin)",
    pacing: "4-5 days",
    headsup: "Daily transactions run almost entirely on WeChat Pay or Alipay; link a foreign card in the app before you arrive, as cash and foreign cards are widely refused."
  },
  {
    id: "xian-terracotta-army",
    name: "Xi'an — Terracotta Army",
    region: "Asia",
    country: "China",
    type: "Wonder",
    weekends: 1,
    costUSD: 750,
    lat: 34.38,
    lng: 109.28,
    blurb: "Eight thousand life-size clay warriors stand guard over a hidden emperor's tomb.",
    wiki: "https://en.wikipedia.org/wiki/Terracotta_Army",
    splurge: false,
    badge: null,
    eat: "Roujiamo — slow-stewed spiced pork stuffed in a crisp griddled flatbread, often called the original Chinese hamburger",
    tip: "Go to the pits early and start with Pit 1, then explore Xi'an's Muslim Quarter food street and cycle the intact Ming-era city walls at dusk.",
    dont: "Do not touch or lean over the railings into the excavation pits; the warriors are fragile, flash-free, and guards strictly enforce the barriers.",
    bestTime: "Spring (March-May) or autumn (September-October) for comfortable weather.",
    phrase: "Xiexie (shyeh-shyeh) — thank you (Mandarin)",
    pacing: "2-3 days",
    headsup: "Use the official public bus 5 (306) from Xi'an railway station to the site and skip the touts steering you to fake 'museums'; carry your passport for ticket entry."
  },
  {
    id: "shanghai",
    name: "Shanghai",
    region: "Asia",
    country: "China",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 31.23,
    lng: 121.47,
    blurb: "Art-deco riverfront meets a galaxy of skyscrapers across the neon-lit Huangpu.",
    wiki: "https://en.wikipedia.org/wiki/Shanghai",
    splurge: false,
    badge: null,
    eat: "Xiaolongbao — delicate steamed soup dumplings filled with pork and hot broth, a Shanghai icon eaten at Nanxiang",
    tip: "Walk the Bund at dusk to watch Pudong's towers light up, then take the Maglev from the airport, the fastest commercial train on earth.",
    dont: "Do not get pulled into a friendly 'tea ceremony' or art-gallery invitation near the Bund or Nanjing Road; it is a notorious overcharging scam targeting foreigners.",
    bestTime: "October-November and March-April, mild and dry between heat and damp cold.",
    phrase: "Xiexie (shyeh-shyeh) — thank you (Mandarin)",
    pacing: "3-4 days",
    headsup: "Set up WeChat Pay or Alipay with a foreign card before arriving; cabs and shops largely skip cash, and remember Western apps need a VPN here."
  },
  {
    id: "guilin-yangshuo",
    name: "Guilin & Yangshuo",
    region: "Asia",
    country: "China",
    type: "Natural",
    weekends: 1,
    costUSD: 750,
    lat: 24.77,
    lng: 110.49,
    blurb: "Mist-wrapped karst peaks mirror in the Li River as cormorant fishermen drift past.",
    wiki: "https://en.wikipedia.org/wiki/Yangshuo_County",
    splurge: false,
    badge: null,
    eat: "Guilin rice noodles — springy rice noodles in a savoury broth with pickles and crisp pork, the region's breakfast staple",
    tip: "Cruise or bamboo-raft the Li River from Guilin to Yangshuo (the scene on the 20-yuan note), then cycle the Yulong River valley among the peaks.",
    dont: "Do not pay the elderly cormorant fishermen for a photo expecting a 'real' catch; many now pose only for tourists, so know it is a staged shot.",
    bestTime: "April-October for greenery; spring mist makes the peaks most ethereal.",
    phrase: "Xiexie (shyeh-shyeh) — thank you (Mandarin)",
    pacing: "3-4 days",
    headsup: "River-cruise water levels drop in dry winter months, sometimes forcing shorter raft sections; book a full-length boat cruise in advance during peak season."
  },
  {
    id: "zhangjiajie-avatar-mountains",
    name: "Zhangjiajie — the Avatar mountains",
    region: "Asia",
    country: "China",
    type: "Natural",
    weekends: 1,
    costUSD: 750,
    lat: 29.32,
    lng: 110.43,
    blurb: "Thousands of sandstone pillars stab through the clouds like floating mountains made real.",
    wiki: "https://en.wikipedia.org/wiki/Zhangjiajie_National_Forest_Park",
    splurge: false,
    badge: null,
    eat: "Tujia sour-fish hotpot — local river fish simmered with the pickled-sour chilli flavours of the indigenous Tujia people",
    tip: "Use the Bailong Glass Elevator and shuttle buses inside the vast park to save your legs, and stay overnight inside to beat the day-tour crowds at the pillars.",
    dont: "Do not assume the towering 'Avatar Hallelujah Mountain' is a quick stop; the park is enormous, so don't underestimate the time and transfers between viewpoints.",
    bestTime: "April-June and September-October; clouds drifting among the pillars are most dramatic.",
    phrase: "Xiexie (shyeh-shyeh) — thank you (Mandarin)",
    pacing: "3-4 days",
    headsup: "The multi-day park ticket links your fingerprint to entry, so the same person must use it each day; the glass bridge and Tianmen Mountain are separate paid sites nearby."
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    region: "Asia",
    country: "Hong Kong",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 22.30,
    lng: 114.17,
    blurb: "A skyline of light rises over the harbour where junks slip between glass towers.",
    wiki: "https://en.wikipedia.org/wiki/Hong_Kong",
    splurge: false,
    badge: null,
    eat: "Dim sum — bamboo baskets of har gow shrimp dumplings and char siu bao, taken at a bustling teahouse yum cha brunch",
    tip: "Buy an Octopus card; it pays for the Star Ferry, MTR, trams, buses and even convenience stores, and ride the vintage Peak Tram up Victoria Peak.",
    dont: "Do not stand on the left of an escalator or dawdle on the MTR; keep left clear for those walking, as the city moves fast and pile-ups annoy locals.",
    bestTime: "October-December, dry, sunny and clear, ideal for the harbour and hiking.",
    phrase: "M-goi (mm-goy) — thank you / please (Cantonese)",
    pacing: "3-4 days",
    headsup: "When tapping a teapot lid at dim sum you are asking for a refill, and tapping two fingers on the table thanks whoever pours your tea; both are everyday etiquette."
  },
  {
    id: "seoul",
    name: "Seoul",
    region: "Asia",
    country: "South Korea",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 37.57,
    lng: 126.98,
    blurb: "Palaces and hanok lanes sit beside K-pop, neon nightlife and sizzling barbecue grills.",
    wiki: "https://en.wikipedia.org/wiki/Seoul",
    splurge: false,
    badge: null,
    eat: "Samgyeopsal — thick pork belly grilled at the table and wrapped in lettuce with garlic, ssamjang and kimchi",
    tip: "Wear a hanbok to enter the royal palaces like Gyeongbokgung free, and use the cheap, immaculate metro with a rechargeable T-money card.",
    dont: "Do not pour your own drink or take it one-handed when an elder pours for you; use two hands and turn slightly away to drink, it is core table respect.",
    bestTime: "April-May and September-October for mild weather and autumn colour or spring blossoms.",
    phrase: "Gamsahamnida (gam-sa-ham-ni-da) — thank you (Korean)",
    pacing: "3-4 days",
    headsup: "Tipping is not customary and can confuse staff; many restaurants are cash- or local-card-only, and there is a curfew-free but intense late-night culture, so pace yourself."
  },
  {
    id: "taipei",
    name: "Taipei",
    region: "Asia",
    country: "Taiwan",
    type: "City",
    weekends: 1,
    costUSD: 750,
    lat: 25.03,
    lng: 121.57,
    blurb: "Steaming night markets, hot-spring valleys and a bamboo-shaped tower under green mountains.",
    wiki: "https://en.wikipedia.org/wiki/Taipei",
    splurge: false,
    badge: null,
    eat: "Beef noodle soup — braised beef shank in a rich star-anise broth with hand-pulled noodles, Taipei's signature bowl",
    tip: "Eat your way through Raohe or Shilin night market, and ride to nearby Beitou for free or cheap public hot springs after a day of walking.",
    dont: "Do not eat, drink or chew gum on the Taipei MRT; it is strictly banned and fined, even for water, unlike on the streets above.",
    bestTime: "October-December, dry and pleasant after the summer typhoon and heat.",
    phrase: "Xiexie (shyeh-shyeh) — thank you (Mandarin)",
    pacing: "3-4 days",
    headsup: "Get an EasyCard for the MRT, buses and convenience stores; durian and strong-smelling food are banned on transit, and most night-market stalls take cash only."
  },
  {
    id: "everest-base-camp-trek",
    name: "Everest Base Camp trek",
    region: "Asia",
    country: "Nepal",
    type: "Trek",
    weekends: 4,
    costUSD: 5000,
    lat: 28.00,
    lng: 86.86,
    blurb: "Two weeks up the Khumbu past Sherpa villages to stand beneath the world's highest peak.",
    wiki: "https://en.wikipedia.org/wiki/Everest_base_camps",
    splurge: true,
    badge: null,
    eat: "Dal bhat — lentil soup, rice and curried vegetables with free refills, the trekker's all-day fuel ('dal bhat power, 24 hour')",
    tip: "Build in acclimatisation days at Namche Bazaar and Dingboche and ascend slowly; the climb-high-sleep-low rhythm is what keeps you safe up here.",
    dont: "Do not walk on the uphill (mountain) side when passing a yak train on narrow trails; stand on the inner side so a startled animal can't nudge you off the edge.",
    bestTime: "October-November or March-April, the stable pre/post-monsoon windows with clear peaks.",
    phrase: "Dhanyabad (dhun-yuh-baad) — thank you (Nepali)",
    pacing: "12-16 days round trip",
    headsup: "The Lukla flight that starts the trek is notoriously weather-delayed; budget spare days, get altitude-cover travel insurance, and carry cash as there are no ATMs up-valley."
  },
  {
    id: "annapurna-circuit",
    name: "Annapurna Circuit",
    region: "Asia",
    country: "Nepal",
    type: "Trek",
    weekends: 4,
    costUSD: 4200,
    lat: 28.80,
    lng: 83.94,
    blurb: "Circle a Himalayan massif from rice paddies over the 5,416m Thorong La pass.",
    wiki: "https://en.wikipedia.org/wiki/Annapurna_Circuit",
    splurge: true,
    badge: null,
    eat: "Thukpa — a hearty Tibetan-style noodle soup with vegetables or meat, warming in the cold mountain teahouses",
    tip: "Cross the high Thorong La pass at first light from Thorong Phedi or High Camp; afternoon winds and weather make a late crossing dangerous.",
    dont: "Do not skip the acclimatisation stop before the pass to save a day; rushing the altitude gain is the classic, sometimes fatal, mistake here.",
    bestTime: "October-November or March-April for clear, stable trekking weather.",
    phrase: "Namaste (nuh-muh-stay) — hello / greetings (Nepali)",
    pacing: "12-18 days depending on side trips",
    headsup: "You need both a TIMS card and an ACAP permit, arranged in Kathmandu or Pokhara; a new road now reaches parts of the trail, so research which sections to walk or jeep."
  },
  {
    id: "trans-siberian-railway",
    name: "Trans-Siberian Railway",
    region: "Asia",
    country: "Russia",
    type: "Rail",
    weekends: 3,
    costUSD: 2650,
    lat: 52.29,
    lng: 104.30,
    blurb: "Roll for thousands of kilometres across the taiga, glimpsing Lake Baikal from your bunk.",
    wiki: "https://en.wikipedia.org/wiki/Trans-Siberian_Railway",
    splurge: false,
    badge: null,
    eat: "Omul — a smoked endemic whitefish from Lake Baikal, sold hot by babushkas on the Listvyanka platforms",
    tip: "Bring tea, instant noodles and snacks; every carriage has a samovar of free boiling water, the social heart of long-distance Russian train life.",
    dont: "Do not ignore the provodnitsa (carriage attendant); she runs your wagon, and staying on her good side keeps your berth, bedding and tea sorted for days.",
    bestTime: "June-September for milder weather and a possible Baikal swim; winter is spectacular but brutally cold.",
    phrase: "Spasibo (spa-see-ba) — thank you (Russian)",
    pacing: "14-21 days with stops",
    headsup: "Check current travel advisories and visa rules carefully before booking; the trains run on Moscow time the whole route, so confirm local times for every stop and stretch your legs only as long as scheduled."
  },
  {
    id: "silk-road-samarkand-bukhara",
    name: "Silk Road — Samarkand & Bukhara",
    region: "Asia",
    country: "Uzbekistan",
    type: "City",
    weekends: 2,
    costUSD: 1500,
    lat: 39.65,
    lng: 66.96,
    blurb: "Turquoise-tiled madrasas and domes blaze across the great caravan cities of Central Asia.",
    wiki: "https://en.wikipedia.org/wiki/Samarkand",
    splurge: false,
    badge: null,
    eat: "Plov — fragrant rice slow-cooked with mutton, carrots and cumin in a giant kazan, Uzbekistan's national pride",
    tip: "Ride the fast Afrosiyob train between Tashkent, Samarkand and Bukhara; it is comfortable, cheap and saves long desert road hours.",
    dont: "Do not climb on or lean against the ancient tilework of the Registan or photograph people without asking; the mosaics are fragile and hospitality is sincere, not a show.",
    bestTime: "April-May or September-October, avoiding the scorching summer and cold winter.",
    phrase: "Rahmat (rah-mat) — thank you (Uzbek)",
    pacing: "7-10 days",
    headsup: "Carry cash (US dollars exchange well) as cards are patchy outside big hotels, and keep your hotel registration slips, as you may be asked for them on departure.",
  },
];
