// Europe — World Bucket List data (auto-generated, hand-tuned facts)
window.WBL_EUROPE = [
  {
    id: "paris-versailles-louvre",
    name: "Paris, Versailles & the Louvre",
    region: "Europe",
    country: "France",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 48.86,
    lng: 2.34,
    blurb: "Hall of Mirrors gold, the Mona Lisa's smirk, and zinc rooftops blushing at dusk.",
    wiki: "https://en.wikipedia.org/wiki/Paris",
    splurge: false,
    badge: null,
    eat: "Jambon-beurre — crusty baguette, ham and salted butter, the classic counter lunch",
    tip: "Always open with 'Bonjour' before any request in a shop; skipping it reads as rude.",
    dont: "Don't expect free tap-water unless you ask for 'une carafe d'eau' — otherwise you pay for bottled.",
    bestTime: "May-June or September — mild light, gardens in bloom, fewer August closures.",
    phrase: "L'addition, s'il vous plaît — the bill, please",
    pacing: "3-4 days",
    headsup: "Buy timed Louvre and Versailles tickets online; walk-up queues can swallow hours, and Versailles shuts Mondays."
  },
  {
    id: "london-stonehenge",
    name: "London & Stonehenge",
    region: "Europe",
    country: "United Kingdom",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 51.51,
    lng: -0.13,
    blurb: "Neolithic stones at dawn, then double-deckers and gilded pubs glowing through the drizzle.",
    wiki: "https://en.wikipedia.org/wiki/London",
    splurge: false,
    badge: null,
    eat: "Sunday roast — slow beef, Yorkshire pudding and gravy, a pub ritual best after noon",
    tip: "Stand on the right on Tube escalators so commuters can stride past on the left.",
    dont: "Don't barge onto the carriage before passengers exit — Londoners queue obsessively, even informally.",
    bestTime: "May-September for long daylight; Stonehenge solstice draws crowds in late June.",
    phrase: "Cheers — slang for thanks (and goodbye, and bottoms-up)",
    pacing: "3-4 days",
    headsup: "Stonehenge has no public transport from London; book a tour or hire a car, and reserve a timed slot."
  },
  {
    id: "rome-vatican-colosseum",
    name: "Rome, Vatican & Colosseum",
    region: "Europe",
    country: "Italy",
    type: "Wonder",
    weekends: 1,
    costUSD: 580,
    lat: 41.89,
    lng: 12.49,
    blurb: "Gladiator arches, Sistine ceilings, and espresso slammed standing at a marble bar.",
    wiki: "https://en.wikipedia.org/wiki/Colosseum",
    splurge: false,
    badge: "new7",
    eat: "Cacio e pepe — spaghetti bound in pecorino romano and cracked black pepper, nothing else",
    tip: "Drink from the nasoni street fountains; cap the spout with your palm and water arcs up to sip.",
    dont: "Don't bare shoulders or knees at St Peter's or you'll be turned away at the door.",
    bestTime: "April-May or October — warm but before the searing, packed summer.",
    phrase: "Un caffè, per favore — an espresso, please",
    pacing: "3-4 days",
    headsup: "Colosseum and Vatican tickets sell out days ahead; book timed entry and skip the touts reselling at the gate."
  },
  {
    id: "florence-pisa",
    name: "Florence & Pisa",
    region: "Europe",
    country: "Italy",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 43.77,
    lng: 11.26,
    blurb: "Brunelleschi's terracotta dome over Renaissance lanes, then Pisa's tower defying gravity.",
    wiki: "https://en.wikipedia.org/wiki/Florence",
    splurge: false,
    badge: null,
    eat: "Bistecca alla fiorentina — thick T-bone grilled rare over chestnut embers, sold by weight",
    tip: "Order a 'fiorentina' rare; asking for it well-done genuinely offends Florentine butchers.",
    dont: "Don't sit on the Duomo or church steps to eat — the city fines picnicking in the historic centre.",
    bestTime: "April-June or September-October — clear skies before the August heat haze.",
    phrase: "Quant'e? — how much is it?",
    pacing: "2-3 days",
    headsup: "Climbing the Duomo cupola requires a separate timed reservation that books out fast; the Uffizi needs one too."
  },
  {
    id: "venice-gondolas",
    name: "Venice & the gondolas",
    region: "Europe",
    country: "Italy",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 45.44,
    lng: 12.34,
    blurb: "Sinking palazzi, lapping canals, and dawn light gilding the Grand Canal before the crowds.",
    wiki: "https://en.wikipedia.org/wiki/Venice",
    splurge: false,
    badge: null,
    eat: "Cicchetti — bite-size bar snacks like baccala mantecato on crostini, with a small 'ombra' wine",
    tip: "Stand at the bar for your spritz and cicchetti; sitting at a table can triple the price.",
    dont: "Don't feed pigeons in St Mark's Square — it's banned and fineable.",
    bestTime: "April-May or September-October; avoid summer crowds and autumn 'acqua alta' floods.",
    phrase: "Dov'e il vaporetto? — where is the water bus?",
    pacing: "2 days",
    headsup: "A day-tripper access fee now applies on peak days; gondola rides have fixed official rates, so agree before stepping in."
  },
  {
    id: "milan-lake-como",
    name: "Milan & Lake Como",
    region: "Europe",
    country: "Italy",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 45.46,
    lng: 9.19,
    blurb: "The Duomo's marble spires, Da Vinci's Last Supper, then villa gardens above mirror-still Como.",
    wiki: "https://en.wikipedia.org/wiki/Milan",
    splurge: false,
    badge: null,
    eat: "Risotto alla milanese — saffron-stained, marrow-rich rice, golden and creamy",
    tip: "Join aperitivo around 7pm; one drink buys access to a generous buffet of snacks.",
    dont: "Don't order a cappuccino after lunch — milanesi consider milky coffee a morning-only thing.",
    bestTime: "April-June or September; Como's gardens peak in late spring.",
    phrase: "Un aperitivo, grazie — an aperitif, thanks",
    pacing: "2-3 days",
    headsup: "Last Supper tickets are scarce and timed to 15-minute slots; book weeks ahead or via an official tour."
  },
  {
    id: "cinque-terre",
    name: "Cinque Terre",
    region: "Europe",
    country: "Italy",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 44.13,
    lng: 9.71,
    blurb: "Five pastel villages stacked on cliffs above a sea so blue it looks edited.",
    wiki: "https://en.wikipedia.org/wiki/Cinque_Terre",
    splurge: false,
    badge: null,
    eat: "Trofie al pesto — twisty pasta with Ligurian basil pesto, potatoes and green beans",
    tip: "Buy the Cinque Terre Card; it bundles unlimited trains between the villages and the trail fees.",
    dont: "Don't hike the coastal path in flip-flops — rangers turn back tourists in unsuitable footwear.",
    bestTime: "May-June or September — warm sea, open trails, before the August crush.",
    phrase: "A che ora parte il treno? — what time does the train leave?",
    pacing: "2 days",
    headsup: "The famous Via dell'Amore and some trails close after landslides; check daily status before you set out."
  },
  {
    id: "amalfi-positano-capri",
    name: "Amalfi Coast, Positano & Capri",
    region: "Europe",
    country: "Italy",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 40.63,
    lng: 14.60,
    blurb: "Lemon groves, vertiginous switchbacks, and Positano tumbling pink and white into the Tyrrhenian.",
    wiki: "https://en.wikipedia.org/wiki/Amalfi_Coast",
    splurge: false,
    badge: null,
    eat: "Delizia al limone — sponge dome soaked in Sorrento lemon cream, sharp and silky",
    tip: "Travel the coast by ferry, not car; the cliff road is gridlocked and parking is brutal.",
    dont: "Don't try to drive into the towns in summer — many ban non-resident cars and tow offenders.",
    bestTime: "May-June or September — swimmable sea without peak gridlock.",
    phrase: "Due biglietti per il traghetto — two ferry tickets",
    pacing: "3 days",
    headsup: "Capri's Blue Grotto only opens in calm seas and closes without warning; cash is needed for the rowboat entry."
  },
  {
    id: "matera",
    name: "Matera",
    region: "Europe",
    country: "Italy",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 40.67,
    lng: 16.61,
    blurb: "Ancient cave dwellings glowing honey-gold at dusk, one of Earth's oldest lived-in cities.",
    wiki: "https://en.wikipedia.org/wiki/Matera",
    splurge: false,
    badge: null,
    eat: "Pane di Matera — huge horn-shaped sourdough with a thick crust, IGP-protected",
    tip: "Wear grippy shoes; the Sassi are a maze of uneven stone steps and ramps, slick when wet.",
    dont: "Don't treat inhabited cave homes as photo props — peer into private doorways and you'll rile residents.",
    bestTime: "April-June or September-October; midday summer sun bakes the stone.",
    phrase: "Dove sono i Sassi? — where are the Sassi cave quarters?",
    pacing: "1-2 days",
    headsup: "Matera has no airport and limited trains; most arrive by bus or car from Bari, roughly an hour away."
  },
  {
    id: "sicily-etna-taormina",
    name: "Sicily — Etna & Taormina",
    region: "Europe",
    country: "Italy",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 37.85,
    lng: 15.29,
    blurb: "A smoking volcano behind a Greek theatre, the Ionian sea shimmering far below.",
    wiki: "https://en.wikipedia.org/wiki/Taormina",
    splurge: false,
    badge: null,
    eat: "Granita con brioche — slushed almond or coffee ice scooped into a soft sweet bun for breakfast",
    tip: "Eat granita for breakfast like locals; pair almond granita with a warm brioche col tuppo.",
    dont: "Don't climb high on Etna without a certified guide near the summit craters — access is restricted for safety.",
    bestTime: "May-June or September-October — gentle heat, swimmable sea, active but accessible volcano.",
    phrase: "Una granita alla mandorla — an almond granita",
    pacing: "2-3 days",
    headsup: "Etna's summit zones can close on short notice during eruptions; ash also grounds Catania flights occasionally."
  },
  {
    id: "barcelona-sagrada-familia",
    name: "Barcelona & the Sagrada Família",
    region: "Europe",
    country: "Spain",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 41.40,
    lng: 2.17,
    blurb: "Gaudi's impossible basilica drips like candle wax above tapas bars and Mediterranean light.",
    wiki: "https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia",
    splurge: false,
    badge: null,
    eat: "Pa amb tomaquet — rustic bread rubbed with ripe tomato, olive oil and salt, a Catalan staple",
    tip: "Lunch and dinner run late here; restaurants fill around 2pm and 9pm, not before.",
    dont: "Don't assume everything is 'Spanish' — Catalans are proud of Catalan language and identity, so acknowledge it.",
    bestTime: "May-June or September — warm, beachable, before peak August tourism.",
    phrase: "Gracies — thank you (Catalan, 'GRAH-syes')",
    pacing: "3 days",
    headsup: "Pickpockets work La Rambla and the metro hard; keep bags zipped and front-facing in crowds."
  },
  {
    id: "madrid-toledo",
    name: "Madrid & Toledo",
    region: "Europe",
    country: "Spain",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 40.42,
    lng: -3.70,
    blurb: "Velazquez and Goya by day, then a medieval city of three faiths crowning a river bend.",
    wiki: "https://en.wikipedia.org/wiki/Madrid",
    splurge: false,
    badge: null,
    eat: "Cocido madrileno — a slow chickpea and meat stew served in courses, the city's winter soul",
    tip: "The Prado is free in its last two evening hours daily; arrive early for the queue.",
    dont: "Don't plan dinner at 7pm — kitchens often open at 8:30 or 9, and earlier marks you as a tourist.",
    bestTime: "April-June or September-October; Madrid summers are scorching and many flee.",
    phrase: "Una cana, por favor — a small draft beer, please",
    pacing: "2-3 days",
    headsup: "Toledo is a 33-minute high-speed train from Madrid but trains sell out; book the AVE seat in advance."
  },
  {
    id: "granada-seville-alhambra",
    name: "Granada & Seville — the Alhambra",
    region: "Europe",
    country: "Spain",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 37.18,
    lng: -3.59,
    blurb: "Moorish palaces carved like lace, then Seville's orange-scented patios and pounding flamenco.",
    wiki: "https://en.wikipedia.org/wiki/Alhambra",
    splurge: false,
    badge: null,
    eat: "Salmorejo — thick chilled Cordoban tomato cream topped with egg and jamon, richer than gazpacho",
    tip: "In Granada, many bars still bring a free tapa with every drink you order — so bar-hop and graze.",
    dont: "Don't clap along loudly at a serious flamenco show — wait for the 'ole', as off-beat clapping disrupts the rhythm.",
    bestTime: "March-May or October — Andalusia bakes brutally in midsummer.",
    phrase: "Otra cana, por favor — another small beer, please",
    pacing: "3 days",
    headsup: "Alhambra Nasrid Palaces have a strict timed entry stamped on your ticket; sell out weeks ahead and you can't change the slot."
  },
  {
    id: "lisbon-sintra",
    name: "Lisbon & Sintra",
    region: "Europe",
    country: "Portugal",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 38.72,
    lng: -9.14,
    blurb: "Yellow trams grinding up tiled hills, then Sintra's fairy-tale palaces lost in misty forest.",
    wiki: "https://en.wikipedia.org/wiki/Lisbon",
    splurge: false,
    badge: null,
    eat: "Pastel de nata — warm custard tart with a flaky shell, dusted with cinnamon, best from Belem",
    tip: "Grab a rechargeable Viva Viagem card; it covers trams, metro and the Sintra train cheaply.",
    dont: "Don't order a 'bica' expecting a big coffee — it's a tiny espresso, the Lisbon default.",
    bestTime: "April-June or September-October — sunny and mild without summer crowds.",
    phrase: "Obrigado / Obrigada — thank you (men say -o, women -a)",
    pacing: "3 days",
    headsup: "Sintra's Pena Palace requires a timed ticket and the shuttle bus 434 jams up; go at opening to beat the queue."
  },
  {
    id: "porto",
    name: "Porto",
    region: "Europe",
    country: "Portugal",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 41.15,
    lng: -8.61,
    blurb: "Port-wine lodges across the Douro, azulejo tiles and a riverside that glows at golden hour.",
    wiki: "https://en.wikipedia.org/wiki/Porto",
    splurge: false,
    badge: null,
    eat: "Francesinha — a meat-stacked sandwich drowned in spicy beer-and-tomato cheese sauce, a fork-and-knife affair",
    tip: "Cross to Vila Nova de Gaia for the port cellar tastings; the famous lodges sit on the far bank.",
    dont: "Don't call the locals 'Portuenses' wrong or confuse port styles — ask tawny vs ruby and they'll happily school you.",
    bestTime: "May-June or September-October; the Douro harvest makes September special.",
    phrase: "Um vinho do Porto, por favor — a glass of port wine, please",
    pacing: "2-3 days",
    headsup: "Many port lodges require a booked tasting slot, and the steep riverside steps are exhausting; wear real shoes."
  },
  {
    id: "amsterdam-giethoorn",
    name: "Amsterdam & Giethoorn",
    region: "Europe",
    country: "Netherlands",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 52.37,
    lng: 4.90,
    blurb: "Canal-ring gables and bike bells, then a car-free village laced only with footbridges and water.",
    wiki: "https://en.wikipedia.org/wiki/Amsterdam",
    splurge: false,
    badge: null,
    eat: "Haring — raw herring with onions and pickles, tipped back by the tail at a street stall",
    tip: "Never walk in the red bike lanes; cyclists rule the road and won't slow for dawdlers.",
    dont: "Don't photograph people in the Red Light District — it's banned, and bouncers enforce it firmly.",
    bestTime: "April for tulips and King's Day, or May-September for canal-side warmth.",
    phrase: "Dank je wel — thank you ('dank yuh vel')",
    pacing: "2-3 days",
    headsup: "Giethoorn is about 1.5 hours away by train and bus; whisper-boat rentals book up on summer weekends."
  },
  {
    id: "bruges-brussels",
    name: "Bruges & Brussels",
    region: "Europe",
    country: "Belgium",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 51.21,
    lng: 3.22,
    blurb: "Bruges' canals and step-gabled squares, then Brussels' golden Grand-Place and waffle-scented air.",
    wiki: "https://en.wikipedia.org/wiki/Bruges",
    splurge: false,
    badge: null,
    eat: "Moules-frites — a steaming pot of mussels with crisp twice-fried chips and mayo",
    tip: "Belgian fries come with mayo, not ketchup; order them from a 'frituur' kiosk for the real thing.",
    dont: "Don't lump Flanders and Wallonia together — language pride runs deep, so let people lead in Dutch or French.",
    bestTime: "April-June or September; Bruges is enchanting and quieter outside summer.",
    phrase: "Een biertje, alstublieft — a beer, please (Dutch)",
    pacing: "2 days",
    headsup: "Many shops and museums close Mondays; carry coins, as some public toilets and small cafes are cash-only."
  },
  {
    id: "berlin",
    name: "Berlin",
    region: "Europe",
    country: "Germany",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 52.52,
    lng: 13.40,
    blurb: "Cold-War scars turned street art, all-night clubs, and history hanging heavy in every block.",
    wiki: "https://en.wikipedia.org/wiki/Berlin",
    splurge: false,
    badge: null,
    eat: "Currywurst — sliced sausage doused in curried ketchup, the city's beloved street snack",
    tip: "Validate your transit ticket in the platform machine before boarding; inspectors fine on the spot.",
    dont: "Don't pose or joke at the Holocaust Memorial — climbing the stelae for selfies is deeply disrespectful.",
    bestTime: "May-September for beer gardens and lakes; the city is grey but lively in winter.",
    phrase: "Entschuldigung — excuse me / sorry",
    pacing: "3 days",
    headsup: "Top clubs like Berghain have strict, unpredictable door policies; many venues are cash-only inside."
  },
  {
    id: "munich-neuschwanstein",
    name: "Munich & Neuschwanstein",
    region: "Europe",
    country: "Germany",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 48.14,
    lng: 11.58,
    blurb: "Beer-hall sing-alongs in the city, then a turreted fairy-tale castle floating above Alpine pines.",
    wiki: "https://en.wikipedia.org/wiki/Neuschwanstein_Castle",
    splurge: false,
    badge: null,
    eat: "Weisswurst — pale veal sausage with sweet mustard and a pretzel, eaten before noon",
    tip: "At a beer garden you may bring your own food to the unclothed tables, but must buy the beer there.",
    dont: "Don't try to clink and drink without eye contact at toasts — Bavarians find a wandering gaze unlucky and rude.",
    bestTime: "May-September for beer gardens; late September for Oktoberfest if you book far ahead.",
    phrase: "Ein Mass, bitte — a one-litre beer, please",
    pacing: "3 days",
    headsup: "Neuschwanstein interior is by timed guided tour only and sells out; reserve online and arrive early for the uphill walk."
  },
  {
    id: "romantic-road-rothenburg-cologne",
    name: "Romantic Road — Rothenburg & Cologne",
    region: "Europe",
    country: "Germany",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 49.38,
    lng: 10.18,
    blurb: "Half-timbered Rothenburg frozen in the Middle Ages, ending at Cologne's soaring twin-spired cathedral.",
    wiki: "https://en.wikipedia.org/wiki/Rothenburg_ob_der_Tauber",
    splurge: false,
    badge: null,
    eat: "Schneeball — a fist-size ball of fried shortcrust ribbons dusted in sugar, Rothenburg's signature sweet",
    tip: "Join the night-watchman's evening tour in Rothenburg; it's the town's most atmospheric hour.",
    dont: "Don't honk or jaywalk against a red pedestrian light — Germans wait even on empty streets and frown on it.",
    bestTime: "May-September for greenery; December for Rothenburg's famous Christmas market.",
    phrase: "Wo ist der Marktplatz? — where is the market square?",
    pacing: "2-3 days",
    headsup: "The route is best by car; public transport between small towns is sparse, and Cologne's cathedral towers shut in bad weather."
  },
  {
    id: "hamburg",
    name: "Hamburg",
    region: "Europe",
    country: "Germany",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 53.55,
    lng: 9.99,
    blurb: "A salt-aired harbour city of red-brick warehouses, glassy concert hall and Reeperbahn neon.",
    wiki: "https://en.wikipedia.org/wiki/Hamburg",
    splurge: false,
    badge: null,
    eat: "Fischbrotchen — a crusty roll stuffed with pickled herring or fried fish, eaten dockside",
    tip: "Catch the public ferry line 62 from Landungsbrucken; it's a harbour cruise for the price of a transit ticket.",
    dont: "Don't wander the Reeperbahn flashing valuables late at night — it's lively but a known spot for petty theft scams.",
    bestTime: "May-September for harbour life and long evenings; expect wind and rain year-round.",
    phrase: "Moin — northern German hello, used any time of day",
    pacing: "2 days",
    headsup: "Elbphilharmonie's free Plaza viewpoint needs a timed (free) ticket, and concerts sell out months ahead."
  },
  {
    id: "prague-cesky-krumlov",
    name: "Prague & Český Krumlov",
    region: "Europe",
    country: "Czech Republic",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 50.09,
    lng: 14.42,
    blurb: "A hundred Gothic spires, the medieval Charles Bridge at dawn, and a storybook castle town downstream.",
    wiki: "https://en.wikipedia.org/wiki/Prague",
    splurge: false,
    badge: null,
    eat: "Svickova — beef sirloin in creamy root-vegetable sauce with bread dumplings and cranberry",
    tip: "Czech beer is cheaper than water and superb; order by saying 'pivo' and it'll be a half-litre.",
    dont: "Don't change money at street kiosks offering great rates — they're notorious scams; use a bank ATM.",
    bestTime: "April-June or September-October; summer floods the Old Town with tour groups.",
    phrase: "Dekuji (DYE-koo-yi) — thank you",
    pacing: "3 days",
    headsup: "Taxis hailed near tourist spots overcharge wildly; use a ride app, and validate tram tickets when boarding."
  },
  {
    id: "vienna-salzburg-hallstatt",
    name: "Vienna, Salzburg & Hallstatt",
    region: "Europe",
    country: "Austria",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 48.21,
    lng: 16.37,
    blurb: "Imperial palaces and waltz halls, Mozart's Salzburg, and a lakeside village mirrored in glass-still water.",
    wiki: "https://en.wikipedia.org/wiki/Vienna",
    splurge: false,
    badge: null,
    eat: "Sachertorte — dense dark chocolate cake with apricot jam, served with unsweetened whipped cream",
    tip: "Linger in a traditional coffeehouse; ordering one melange buys you hours and a free glass of water.",
    dont: "Don't skip titles in formal settings — Austrians value courtesy, so a proper 'Gruss Gott' and politeness go far.",
    bestTime: "May-June or September; Hallstatt is serene before summer day-trip buses arrive.",
    phrase: "Gruss Gott — Austrian/Bavarian hello ('groos got')",
    pacing: "4-5 days",
    headsup: "Tiny Hallstatt limits day visitors and bans tour buses at times; arrive early or stay overnight to enjoy it calmly."
  },
  {
    id: "budapest",
    name: "Budapest",
    region: "Europe",
    country: "Hungary",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 47.50,
    lng: 19.04,
    blurb: "Thermal baths steaming under neo-Gothic spires, the Danube splitting hilly Buda from flat Pest.",
    wiki: "https://en.wikipedia.org/wiki/Budapest",
    splurge: false,
    badge: null,
    eat: "Gulyas — a paprika-spiced beef and vegetable soup, hearty and far thinner than foreign 'goulash'",
    tip: "Bring flip-flops and a swim cap option for the thermal baths; rent a cabin for valuables.",
    dont: "Don't clink beer glasses when toasting — an old tradition tied to 1849 makes it taboo for many Hungarians.",
    bestTime: "April-June or September-October; the baths are blissful in cool weather.",
    phrase: "Koszonom (KUH-suh-nuhm) — thank you",
    pacing: "2-3 days",
    headsup: "Some 'ruin bar' areas and taxis target tourists with padded bills; agree fares or use the official Fotaxi/app."
  },
  {
    id: "krakow-auschwitz",
    name: "Kraków & Auschwitz",
    region: "Europe",
    country: "Poland",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 50.06,
    lng: 19.94,
    blurb: "A golden medieval square and royal castle, near a memorial that asks the world never to forget.",
    wiki: "https://en.wikipedia.org/wiki/Krak%C3%B3w",
    splurge: false,
    badge: null,
    eat: "Pierogi — soft dumplings filled with potato-cheese, meat or seasonal fruit, boiled then pan-fried",
    tip: "Reserve a free entry slot for the Auschwitz-Birkenau Memorial well ahead; afternoon visits are self-guided.",
    dont: "Don't treat Auschwitz as a photo backdrop or speak loudly there — it is a place of mourning, so dress and behave soberly.",
    bestTime: "May-September for Krakow; the memorial is moving in any season but harsh in deep winter.",
    phrase: "Dziekuje (jen-KOO-yeh) — thank you",
    pacing: "2-3 days",
    headsup: "Auschwitz is about 1.5 hours from Krakow; entry is free but timed tickets vanish fast, so book online in advance."
  },
  {
    id: "athens-meteora",
    name: "Athens & Meteora",
    region: "Europe",
    country: "Greece",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 37.97,
    lng: 23.73,
    blurb: "The Parthenon crowning Athens, then monasteries perched impossibly atop sheer rock pillars.",
    wiki: "https://en.wikipedia.org/wiki/Acropolis_of_Athens",
    splurge: false,
    badge: null,
    eat: "Souvlaki — grilled skewered meat wrapped in pita with tomato, onion and tzatziki, cheap and perfect",
    tip: "Visit the Acropolis at opening or late afternoon; midday heat on the marble is brutal and shadeless.",
    dont: "Don't wear stiletto heels or stilettos at the Acropolis — they're banned to protect the ancient stone.",
    bestTime: "April-June or September-October; Greek summers are blistering.",
    phrase: "Efharisto (ef-ha-ri-STO) — thank you",
    pacing: "3 days",
    headsup: "Meteora's monasteries enforce modest dress (covered shoulders and knees, skirts for women) and close on rotating days."
  },
  {
    id: "santorini-mykonos",
    name: "Santorini & Mykonos",
    region: "Europe",
    country: "Greece",
    type: "Island",
    weekends: 1,
    costUSD: 580,
    lat: 36.42,
    lng: 25.43,
    blurb: "Whitewashed caldera villages blazing pink at sunset, then Mykonos' windmills and turquoise coves.",
    wiki: "https://en.wikipedia.org/wiki/Santorini",
    splurge: false,
    badge: null,
    eat: "Fava Santorinis — silky split-pea puree with olive oil and capers, made from the island's volcanic legume",
    tip: "Catch Oia's sunset from a side lane, not the packed castle; crowds arrive an hour early for the prime spots.",
    dont: "Don't throw paper into the toilet — old island plumbing means it goes in the bin beside the bowl.",
    bestTime: "May-June or September — warm seas without the August stampede.",
    phrase: "Kalimera (ka-li-ME-ra) — good morning",
    pacing: "3-4 days",
    headsup: "Inter-island ferries are weather-dependent and can cancel; build a buffer day before any onward flight."
  },
  {
    id: "istanbul-hagia-sophia-blue-mosque",
    name: "Istanbul — Hagia Sophia & Blue Mosque",
    region: "Europe",
    country: "Turkey",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 41.01,
    lng: 28.98,
    blurb: "Two continents, a Byzantine dome and Ottoman minarets, the Bosphorus glinting between mosque calls.",
    wiki: "https://en.wikipedia.org/wiki/Hagia_Sophia",
    splurge: false,
    badge: null,
    eat: "Balik ekmek — grilled mackerel in bread sold from boats by the Galata Bridge, dressed with onion and lemon",
    tip: "Carry a scarf to cover shoulders (and hair for women) before entering working mosques.",
    dont: "Don't visit the Blue Mosque during the five daily prayer times — entry pauses, especially midday Friday.",
    bestTime: "April-May or September-October; summer is hot and the city very crowded.",
    phrase: "Tesekkur ederim (te-shek-KOOR ed-er-im) — thank you",
    pacing: "3 days",
    headsup: "Friendly strangers offering tea or a shoeshine sometimes lead to overpriced bar scams; be polite but wary near tourist sites."
  },
  {
    id: "cappadocia-pamukkale",
    name: "Cappadocia balloon & Pamukkale",
    region: "Europe",
    country: "Turkey",
    type: "Experience",
    weekends: 1,
    costUSD: 870,
    lat: 38.64,
    lng: 34.83,
    blurb: "Hundreds of balloons drifting over fairy-chimney valleys, then snow-white travertine terraces of warm water.",
    wiki: "https://en.wikipedia.org/wiki/Cappadocia",
    splurge: false,
    badge: null,
    eat: "Testi kebab — meat and vegetables slow-cooked in a sealed clay pot, cracked open at your table",
    tip: "Book the balloon for your first morning; flights are weather-cancelled often, so a buffer day lets you rebook.",
    dont: "Don't walk on Pamukkale's terraces with shoes — you must go barefoot to protect the fragile travertine.",
    bestTime: "April-June or September-October; winter is scenic but balloons cancel more.",
    phrase: "Merhaba (mer-ha-BA) — hello",
    pacing: "2-3 days",
    headsup: "Balloon flights start before dawn and sell out in peak season; only certified operators are insured, so verify before paying."
  },
  {
    id: "dubrovnik-plitvice",
    name: "Dubrovnik & Plitvice Lakes",
    region: "Europe",
    country: "Croatia",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 42.64,
    lng: 18.11,
    blurb: "Marble-walled Dubrovnik above the Adriatic, then turquoise lakes cascading through emerald forest.",
    wiki: "https://en.wikipedia.org/wiki/Dubrovnik",
    splurge: false,
    badge: null,
    eat: "Crni rizot — black cuttlefish-ink risotto, briny and glistening, an Adriatic coastal classic",
    tip: "Walk Dubrovnik's city walls right at opening; midday sun is fierce and the narrow ramparts clog with cruise crowds.",
    dont: "Don't swim or wade in Plitvice's lakes — it's strictly forbidden to protect the travertine ecosystem.",
    bestTime: "May-June or September; July-August bring heat and cruise-ship crushes.",
    phrase: "Hvala (HVA-la) — thank you",
    pacing: "3 days",
    headsup: "Plitvice is over 3 hours from Dubrovnik; buy timed entry online, as summer caps daily visitor numbers."
  },
  {
    id: "bled-ljubljana-kotor",
    name: "Bled, Ljubljana & Kotor",
    region: "Europe",
    country: "Multiple",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 46.36,
    lng: 14.11,
    blurb: "An island church on an emerald lake, a riverside capital, and Kotor's fjord-like bay below black mountains.",
    wiki: "https://en.wikipedia.org/wiki/Lake_Bled",
    splurge: false,
    badge: null,
    eat: "Kremna rezina (kremsnita) — Lake Bled's custard-and-cream vanilla slice with crisp puff pastry",
    tip: "Reach Bled island in a traditional hand-rowed pletna boat; ring the wishing bell inside the church.",
    dont: "Don't confuse Slovenia and Slovakia — locals hear it constantly and it grates; they're proudly distinct countries.",
    bestTime: "May-June or September; alpine lakes and the bay are mildest then.",
    phrase: "Hvala (HVA-la) — thank you (Slovene and Montenegrin)",
    pacing: "4-5 days",
    headsup: "This crosses Slovenia and Montenegro borders; renting a car often beats sparse buses, but check cross-border rental rules."
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    region: "Europe",
    country: "Denmark",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 55.68,
    lng: 12.57,
    blurb: "Candle-lit cafes, the colour-block Nyhavn quay, and design so good it feels effortless.",
    wiki: "https://en.wikipedia.org/wiki/Copenhagen",
    splurge: false,
    badge: null,
    eat: "Smorrebrod — open rye sandwiches layered with pickled herring, remoulade or roast beef, eaten with a knife and fork",
    tip: "Rent a bike and ride like a local; the city is flat, bike-laned and faster than driving.",
    dont: "Don't jaywalk against the red signal — Danes wait patiently and crossing early draws disapproving looks.",
    bestTime: "May-August for long daylight; December for cosy hygge and markets.",
    phrase: "Tak — thank you (just 'tahg')",
    pacing: "2-3 days",
    headsup: "Denmark is largely cashless; cards (and mobile pay) work everywhere, but some places no longer take cash at all."
  },
  {
    id: "stockholm",
    name: "Stockholm",
    region: "Europe",
    country: "Sweden",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 59.33,
    lng: 18.07,
    blurb: "A city woven across fourteen islands, ochre old-town lanes and a salvaged 17th-century warship intact.",
    wiki: "https://en.wikipedia.org/wiki/Stockholm",
    splurge: false,
    badge: null,
    eat: "Kottbullar — Swedish meatballs with cream gravy, lingonberry jam and pressed cucumber",
    tip: "Take a proper 'fika' coffee-and-cinnamon-bun break; it's a daily social ritual, not a quick caffeine fix.",
    dont: "Don't be loud or overly chatty with strangers on transit — Swedes value quiet personal space in public.",
    bestTime: "May-August for endless daylight and archipelago boats; winter days are very short.",
    phrase: "Tack — thank you ('tahk')",
    pacing: "2-3 days",
    headsup: "Sweden is nearly cashless and pricey; many spots take cards only, and alcohol is sold through state Systembolaget shops."
  },
  {
    id: "helsinki",
    name: "Helsinki",
    region: "Europe",
    country: "Finland",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 60.17,
    lng: 24.94,
    blurb: "Pale neoclassical squares, design district boutiques, and steaming public saunas by the Baltic.",
    wiki: "https://en.wikipedia.org/wiki/Helsinki",
    splurge: false,
    badge: null,
    eat: "Karjalanpiirakka — Karelian rye pastry boats filled with rice porridge, topped with egg butter",
    tip: "Try a public sauna and follow the etiquette: shower first, sit naked or wrapped, and keep your voice low.",
    dont: "Don't barge or small-talk loudly with strangers — Finns prize calm and personal space, even in queues.",
    bestTime: "June-August for white nights and ferries; winter is dark but sauna-cosy.",
    phrase: "Kiitos (KEE-tos) — thank you",
    pacing: "2 days",
    headsup: "Take the ferry to Suomenlinna sea fortress on a transit ticket; tap water is excellent, so skip buying bottled."
  },
  {
    id: "reykjavik-golden-circle",
    name: "Reykjavík & the Golden Circle",
    region: "Europe",
    country: "Iceland",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 64.15,
    lng: -21.94,
    blurb: "A colourful far-north capital ringed by geysers, a thundering waterfall and a continental rift.",
    wiki: "https://en.wikipedia.org/wiki/Reykjav%C3%ADk",
    splurge: false,
    badge: null,
    eat: "Pylsa — Icelandic lamb hot dog with crispy and raw onions, ketchup, sweet mustard and remoulade",
    tip: "Shower thoroughly naked before entering any pool or the Blue Lagoon; it's a strict hygiene rule.",
    dont: "Don't buy bottled water — Icelandic tap water is pristine glacial water, and asking for it free is normal.",
    bestTime: "June-August for greenery and long days; September-March for aurora chances.",
    phrase: "Takk — thank you ('tahk')",
    pacing: "2-3 days",
    headsup: "Iceland is very expensive and card-based; the Golden Circle needs a car or tour, and weather shifts fast, so check road conditions."
  },
  {
    id: "dublin",
    name: "Dublin",
    region: "Europe",
    country: "Ireland",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 53.35,
    lng: -6.26,
    blurb: "Literary pubs, the Book of Kells aglow, and live trad fiddle spilling onto cobbled Temple Bar.",
    wiki: "https://en.wikipedia.org/wiki/Dublin",
    splurge: false,
    badge: null,
    eat: "Coddle — a comforting Dublin stew of sausage, bacon, potato and onion simmered slow",
    tip: "Let a pint of Guinness settle for the full two-part pour; rushing it marks you as a tourist.",
    dont: "Don't tip the barman per pint at the bar — round-buying is the custom, and you take turns standing rounds.",
    bestTime: "May-September for milder weather and festivals; pack rain gear regardless.",
    phrase: "Slainte (SLAWN-cha) — cheers / to your health",
    pacing: "2 days",
    headsup: "Temple Bar pubs charge premium prices for pints; locals drink elsewhere, so step a few streets away to pay less."
  },
  {
    id: "edinburgh",
    name: "Edinburgh",
    region: "Europe",
    country: "United Kingdom",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 55.95,
    lng: -3.19,
    blurb: "A brooding clifftop castle, medieval closes, and an extinct volcano you can climb before lunch.",
    wiki: "https://en.wikipedia.org/wiki/Edinburgh",
    splurge: false,
    badge: null,
    eat: "Haggis, neeps and tatties — spiced sheep offal pudding with mashed turnip and potato",
    tip: "Climb Arthur's Seat at sunrise for the whole city laid out below; it's a short, steep volcanic hike.",
    dont: "Don't call a kilt-wearing local 'English' or the whisky 'Scotch whiskey' with an e — both genuinely irk Scots.",
    bestTime: "May-September; August is electric but jammed with the Fringe festival.",
    phrase: "Aye — Scots for yes",
    pacing: "2-3 days",
    headsup: "During the August Fringe, accommodation prices triple and book out months ahead; reserve very early or visit another month."
  },
  {
    id: "alsace-colmar-strasbourg",
    name: "Alsace — Colmar & Strasbourg",
    region: "Europe",
    country: "France",
    type: "Town",
    weekends: 1,
    costUSD: 580,
    lat: 48.08,
    lng: 7.36,
    blurb: "Half-timbered houses in candy colours along flowered canals, France and Germany blended on the plate.",
    wiki: "https://en.wikipedia.org/wiki/Colmar",
    splurge: false,
    badge: null,
    eat: "Tarte flambee (flammekueche) — thin crisp dough with creme fraiche, onions and bacon lardons",
    tip: "Follow the Alsace wine route by car or bike between villages; many growers offer free cellar tastings.",
    dont: "Don't assume Alsace is just 'German' or 'French' — its blended culture and dialect are a proud identity of their own.",
    bestTime: "May-June or September for vineyards; late November-December for Strasbourg's legendary Christmas market.",
    phrase: "Bonjour, je voudrais gouter — hello, I'd like to taste (the wine)",
    pacing: "2-3 days",
    headsup: "Christmas-market season packs trains and hotels; book transport and rooms months ahead and expect dense crowds."
  },
  {
    id: "moscow",
    name: "Moscow",
    region: "Europe",
    country: "Russia",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 55.75,
    lng: 37.62,
    blurb: "Red Square's candy-swirl domes, palatial marble metro stations, and the Kremlin glowering over it all.",
    wiki: "https://en.wikipedia.org/wiki/Moscow",
    splurge: false,
    badge: null,
    eat: "Beef Stroganoff — strips of beef in a sour-cream and mushroom sauce, a Moscow original",
    tip: "Ride the ornate metro as a sightseeing tour; stations like Komsomolskaya are chandeliered palaces.",
    dont: "Don't photograph government buildings, police or the Kremlin guards up close — it can draw official trouble.",
    bestTime: "May-September for mild weather; winter is bitterly cold but magical with snow.",
    phrase: "Spasibo (spa-SEE-ba) — thank you",
    pacing: "3 days",
    headsup: "Check your government's current travel advisories and visa/sanction realities before planning Russia; entry rules shift fast."
  },
  {
    id: "st-petersburg",
    name: "St Petersburg",
    region: "Europe",
    country: "Russia",
    type: "City",
    weekends: 1,
    costUSD: 580,
    lat: 59.94,
    lng: 30.31,
    blurb: "Tsarist palaces along canals, the Hermitage's endless galleries, and white nights that never quite darken.",
    wiki: "https://en.wikipedia.org/wiki/Saint_Petersburg",
    splurge: false,
    badge: null,
    eat: "Pelmeni — small meat-filled dumplings served with sour cream, butter or vinegar",
    tip: "Visit the Hermitage on a weekday morning; the Winter Palace galleries are vast, so prioritise wings in advance.",
    dont: "Don't give an even number of flowers as a gift — even-numbered bouquets are reserved for funerals in Russia.",
    bestTime: "Late June for white nights; May-September for the best weather.",
    phrase: "Pozhaluysta (pa-ZHAL-sta) — please / you're welcome",
    pacing: "3 days",
    headsup: "Check current travel advisories and visa rules for Russia before booking; some river bridges raise nightly, stranding you across the Neva."
  },
  {
    id: "swiss-alps-jungfrau-zermatt-glacier-express",
    name: "Swiss Alps — Jungfrau, Zermatt & Glacier Express",
    region: "Europe",
    country: "Switzerland",
    type: "Rail",
    weekends: 2,
    costUSD: 1960,
    lat: 46.02,
    lng: 7.75,
    blurb: "The Matterhorn's perfect pyramid, glacier panoramas, and a slow scenic train threading the high Alps.",
    wiki: "https://en.wikipedia.org/wiki/Glacier_Express",
    splurge: false,
    badge: null,
    eat: "Raclette — melted Alpine cheese scraped over boiled potatoes, pickles and cured meat",
    tip: "Get a Swiss Travel Pass; it covers trains, boats and many lifts, and discounts the Glacier Express.",
    dont: "Don't be late for a train by even a minute — Swiss rail is punctual to the second and won't wait.",
    bestTime: "June-September for hiking and clear peaks; December-March for skiing.",
    phrase: "Gruezi (GROO-tsee) — Swiss-German hello",
    pacing: "5-7 days",
    headsup: "Zermatt is car-free; park at Tasch and take the shuttle train, and reserve scenic-train seats well ahead in summer."
  },
  {
    id: "norwegian-fjords-trolltunga-preikestolen",
    name: "Norwegian Fjords — Trolltunga & Preikestolen",
    region: "Europe",
    country: "Norway",
    type: "Natural",
    weekends: 2,
    costUSD: 1160,
    lat: 60.12,
    lng: 6.74,
    blurb: "Two slabs of rock jutting over mirror fjords thousands of feet below, earned by long hard hikes.",
    wiki: "https://en.wikipedia.org/wiki/Trolltunga",
    splurge: false,
    badge: null,
    eat: "Fiskesuppe — creamy Norwegian fish soup with salmon, cod and root vegetables",
    tip: "Start the Trolltunga hike early (it's a 10-12 hour round trip) and pack layers; mountain weather turns fast.",
    dont: "Don't underestimate these as easy viewpoints — people are rescued yearly for arriving unprepared in trainers.",
    bestTime: "June-September when the high trails are snow-free and daylight is long.",
    phrase: "Tusen takk — thank you very much ('TOO-sen tahk')",
    pacing: "7-10 days",
    headsup: "Norway is very expensive; tap water is excellent, and Trolltunga may require parking shuttles or a guide outside peak summer."
  },
  {
    id: "lapland-aurora-dogsled-ice-hotel",
    name: "Lapland — aurora, dog-sledding & ice hotel",
    region: "Europe",
    country: "Finland",
    type: "Experience",
    weekends: 2,
    costUSD: 2160,
    lat: 67.85,
    lng: 24.81,
    blurb: "Green auroras rippling over snow, husky teams streaking through white silence, a hotel carved from ice.",
    wiki: "https://en.wikipedia.org/wiki/Lapland_(Finland)",
    splurge: true,
    badge: null,
    eat: "Poronkaristys — sauteed reindeer with mashed potato and lingonberry, the Sami staple",
    tip: "For auroras, get far from town lights and check a forecast app; clear, dark, active nights are best.",
    dont: "Don't pet or approach the sled huskies without the musher's okay — these are working dogs, not pets.",
    bestTime: "December-March for snow and the best aurora odds in the long polar nights.",
    phrase: "Kiitos (KEE-tos) — thank you (Finnish)",
    pacing: "5-7 days",
    headsup: "Bring or rent serious thermal gear; temperatures can drop well below freezing, and aurora tours can be cancelled for cloud."
  },
  {
    id: "iceland-ring-road",
    name: "Iceland Ring Road",
    region: "Europe",
    country: "Iceland",
    type: "RoadTrip",
    weekends: 2,
    costUSD: 1160,
    lat: 64.96,
    lng: -19.02,
    blurb: "One looping highway past waterfalls, black-sand beaches, glacier lagoons and steaming volcanic earth.",
    wiki: "https://en.wikipedia.org/wiki/Route_1_(Iceland)",
    splurge: false,
    badge: null,
    eat: "Kjotsupa — hearty Icelandic lamb-and-vegetable soup, the perfect warm-up between waterfalls",
    tip: "Check road.is and vedur.is daily; wind and storms close roads, and gravel sections need care.",
    dont: "Don't stop your car on the road shoulder for photos — it causes deadly crashes; use marked pull-offs only.",
    bestTime: "June-August for open roads and midnight sun; winter driving is treacherous.",
    phrase: "Godan daginn (GOH-than DY-in) — good day",
    pacing: "8-10 days",
    headsup: "Take gravel-protection and sand-ash insurance on the rental; fuel stations are sparse in the east, so top up often."
  },
  {
    id: "ireland-wild-atlantic-way-cliffs-of-moher",
    name: "Ireland — Wild Atlantic Way & Cliffs of Moher",
    region: "Europe",
    country: "Ireland",
    type: "RoadTrip",
    weekends: 1,
    costUSD: 580,
    lat: 52.97,
    lng: -9.43,
    blurb: "A wild west coast of sheer black cliffs, lonely peninsulas and Atlantic spray on stone walls.",
    wiki: "https://en.wikipedia.org/wiki/Cliffs_of_Moher",
    splurge: false,
    badge: null,
    eat: "Seafood chowder with soda bread — creamy fish-and-mussel soup mopped up with dense brown bread",
    tip: "Drive the coast unhurried; single-track lanes mean pulling into passing places and waving thanks.",
    dont: "Don't cross the safety barriers at the Cliffs of Moher for a photo — the edges crumble and people have died.",
    bestTime: "May-September for milder, longer days; the Atlantic coast is wet and windy year-round.",
    phrase: "Go raibh maith agat (guh rev mah AH-gut) — thank you (Irish)",
    pacing: "5-7 days",
    headsup: "Ireland drives on the left and rural roads are narrow; book the Cliffs of Moher parking slot online in summer to skip queues."
  },
  {
    id: "scottish-highlands-giants-causeway",
    name: "Scottish Highlands & Giant's Causeway",
    region: "Europe",
    country: "United Kingdom",
    type: "Natural",
    weekends: 1,
    costUSD: 580,
    lat: 57.30,
    lng: -5.16,
    blurb: "Glens, lochs and brooding castles, then 40,000 hexagonal basalt columns marching into the sea.",
    wiki: "https://en.wikipedia.org/wiki/Giant%27s_Causeway",
    splurge: false,
    badge: null,
    eat: "Cullen skink — a thick smoked-haddock, potato and onion soup from Scotland's northeast coast",
    tip: "Carry midge repellent in summer; the tiny biting flies swarm at dawn and dusk near water.",
    dont: "Don't pronounce 'loch' as 'lock' — the throaty 'ch' matters, and getting it right earns a nod.",
    bestTime: "May-September for greener glens and fewer closures; midges peak June-August.",
    phrase: "Slainte mhath (SLAN-juh va) — good health / cheers (Scottish Gaelic)",
    pacing: "5-7 days",
    headsup: "The Highlands and Northern Ireland are separated by a ferry crossing; plan the sea leg, and fuel up before remote stretches."
  },
  {
    id: "camino-de-santiago-final-100km",
    name: "Camino de Santiago — final 100 km",
    region: "Europe",
    country: "Spain",
    type: "Trek",
    weekends: 2,
    costUSD: 1160,
    lat: 42.88,
    lng: -8.54,
    blurb: "A centuries-old pilgrim path through Galician hills, ending under the swinging censer of Santiago's cathedral.",
    wiki: "https://en.wikipedia.org/wiki/Camino_de_Santiago",
    splurge: false,
    badge: null,
    eat: "Pulpo a la gallega — boiled octopus on potato dusted with paprika and olive oil, a Galician icon",
    tip: "Collect stamps in your pilgrim 'credencial' twice daily over the last 100 km to earn the Compostela certificate.",
    dont: "Don't blast music or hog the path at dawn — many walk it as a quiet, reflective pilgrimage.",
    bestTime: "May-June or September-October; July-August are hot and the trail crowded.",
    phrase: "Buen Camino — the pilgrims' greeting, 'have a good way'",
    pacing: "5-7 days",
    headsup: "Albergues fill by afternoon in peak season and many are first-come; break in your shoes beforehand to dodge blisters."
  },
  {
    id: "tour-du-mont-blanc",
    name: "Tour du Mont Blanc",
    region: "Europe",
    country: "Multiple",
    type: "Trek",
    weekends: 3,
    costUSD: 1740,
    lat: 45.83,
    lng: 6.86,
    blurb: "A 170 km circuit around Europe's highest massif, looping through France, Italy and Switzerland.",
    wiki: "https://en.wikipedia.org/wiki/Tour_du_Mont_Blanc",
    splurge: false,
    badge: null,
    eat: "Tartiflette — gratin of potatoes, lardons, onions and melted Reblochon cheese, an Alpine refuge favourite",
    tip: "Book mountain refuges months ahead and carry cash; many huts in the high passes don't take cards.",
    dont: "Don't rely on phone signal for navigation — coverage drops in the high cols, so carry a map and check weather daily.",
    bestTime: "Mid-June to mid-September, when the high passes are clear of snow and refuges are open.",
    phrase: "Bonjour / Buongiorno / Gruezi — hello across France, Italy and Switzerland",
    pacing: "10-12 days",
    headsup: "The trek crosses three countries' currencies and refuges; book huts early, and altitude on the passes can sap the unacclimatised."
  }
];
