// North America — World Bucket List data (auto-generated, hand-tuned facts)
window.WBL_NORTH_AMERICA = [
  {
    id: "new-york-liberty-times-square",
    name: "New York — Statue of Liberty & Times Square",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 40.71,
    lng: -74.01,
    blurb: "A copper goddess in the harbor, then a canyon of screens that never sleeps.",
    wiki: "https://en.wikipedia.org/wiki/Statue_of_Liberty",
    splurge: false,
    badge: null,
    eat: "New York bagel — boiled-then-baked, chewy crust, piled with cream cheese and lox",
    tip: "Stand right, walk left on subway stairs and escalators, and never block the doors.",
    dont: "Don't dawdle or photo-stop mid-sidewalk in Midtown; locals will not hide their irritation.",
    bestTime: "September–October, when humidity breaks and the light turns golden.",
    phrase: "\"You good?\" — a casual New York way of asking if you're okay or done.",
    pacing: "3-4 days",
    headsup: "Statue Crown tickets (and Ellis Island ferries) sell out weeks ahead; book the official ferry, not pier hustlers."
  },
  {
    id: "washington-dc",
    name: "Washington DC",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 38.90,
    lng: -77.04,
    blurb: "Marble temples to democracy, free museums, and cherry blossoms framing a mirrored pool.",
    wiki: "https://en.wikipedia.org/wiki/Washington,_D.C.",
    splurge: false,
    badge: null,
    eat: "Half-smoke — a spicy, coarse-ground half-beef half-pork sausage, Ben's Chili Bowl style",
    tip: "Smithsonian museums are entirely free; reserve timed entry online for the busy ones.",
    dont: "Don't stand on the left on Metro escalators; commuters walk the left, stand the right.",
    bestTime: "Late March–April for the Tidal Basin cherry blossoms, or crisp October.",
    phrase: "\"The Hill\" — local shorthand for Congress and Capitol Hill politics.",
    pacing: "2-3 days",
    headsup: "Capitol and White House tours require advance requests; arrange through your embassy weeks out as a foreign visitor."
  },
  {
    id: "niagara-falls",
    name: "Niagara Falls",
    region: "North America",
    country: "Multiple",
    type: "Natural",
    weekends: 1,
    costUSD: 700,
    lat: 43.08,
    lng: -79.07,
    blurb: "Six million cubic feet a minute thunder over the brink into rising mist.",
    wiki: "https://en.wikipedia.org/wiki/Niagara_Falls",
    splurge: false,
    badge: null,
    eat: "Beaver tail — a flat, fried pastry dusted with cinnamon sugar, a Canadian-side treat",
    tip: "The Canadian (Ontario) side has the panoramic Horseshoe Falls view; cross the Rainbow Bridge on foot.",
    dont: "Don't skip checking visa rules before crossing; the US and Canada are separate entries with their own controls.",
    bestTime: "June–August for full boat tours, or winter for surreal ice formations.",
    phrase: "\"Eh?\" — the friendly Canadian tag turning a statement into a question.",
    pacing: "1-2 days",
    headsup: "Bring your passport to walk between countries, and budget cash in both CAD and USD for each side."
  },
  {
    id: "chicago",
    name: "Chicago",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 41.88,
    lng: -87.63,
    blurb: "Skyscrapers reflected in a mirrored bean, blues clubs, and a lake like an inland sea.",
    wiki: "https://en.wikipedia.org/wiki/Chicago",
    splurge: false,
    badge: null,
    eat: "Deep-dish pizza — a buttery cornmeal crust with cheese under chunky tomato sauce",
    tip: "Take the architecture river cruise; it's the city's best one-hour primer on its skyline.",
    dont: "Don't put ketchup on a Chicago hot dog; it's a genuine local taboo, mustard and relish only.",
    bestTime: "Late spring through early fall; winters off Lake Michigan are brutally cold.",
    phrase: "\"The L\" — the elevated rapid-transit trains looping the downtown Loop.",
    pacing: "2-3 days",
    headsup: "Restaurant bills add a city tax and you tip 18–20% on top; servers earn a low base wage here."
  },
  {
    id: "toronto",
    name: "Toronto",
    region: "North America",
    country: "Canada",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 43.65,
    lng: -79.38,
    blurb: "A glass forest under the CN Tower where half the world's languages share a streetcar.",
    wiki: "https://en.wikipedia.org/wiki/Toronto",
    splurge: false,
    badge: null,
    eat: "Peameal bacon sandwich — cornmeal-crusted brined pork loin on a soft bun, St. Lawrence Market classic",
    tip: "Buy a Presto card for the subway, streetcars and buses; tap on and transfers are free for two hours.",
    dont: "Don't assume Toronto is New York's twin; Canadians notice and gently resent the comparison.",
    bestTime: "May–September; patio season and lake breezes make summer the city's best face.",
    phrase: "\"The Six\" — Drake's nickname for Toronto, from its area codes.",
    pacing: "2-3 days",
    headsup: "Sales tax (HST) isn't shown on price tags, so 13% gets added at the register on almost everything."
  },
  {
    id: "vancouver",
    name: "Vancouver",
    region: "North America",
    country: "Canada",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 49.28,
    lng: -123.12,
    blurb: "Glass towers wedged between a rainforest seawall and snow peaks you can ski by noon.",
    wiki: "https://en.wikipedia.org/wiki/Vancouver",
    splurge: false,
    badge: null,
    eat: "Japadog — a Japanese-Canadian hot dog topped with teriyaki, seaweed and Japanese mayo",
    tip: "Rent a bike and ride the full Stanley Park seawall loop; it's flat, scenic and traffic-free.",
    dont: "Don't litter or jaywalk casually; Vancouver enforces both and locals quietly judge offenders.",
    bestTime: "July–September for the dry sunny window; the rest of the year is famously wet.",
    phrase: "\"Toque\" (took) — Canadian word for a warm knit winter beanie.",
    pacing: "2-3 days",
    headsup: "Cannabis is legal but public smoking is restricted; tobacco-style rules apply, so don't light up just anywhere."
  },
  {
    id: "los-angeles",
    name: "Los Angeles",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 34.05,
    lng: -118.24,
    blurb: "Palm-lined sprawl from Venice surf to Hollywood lights, lived entirely behind the wheel.",
    wiki: "https://en.wikipedia.org/wiki/Los_Angeles",
    splurge: false,
    badge: null,
    eat: "Korean-Mexican taco — Korean BBQ short rib in a tortilla, the Kogi truck original",
    tip: "Rent a car; LA's neighborhoods sprawl for miles and transit covers only a fraction.",
    dont: "Don't expect to walk between sights; treating LA like a compact European city wrecks your day.",
    bestTime: "March–May or September–November dodge both summer crowds and wildfire-smoke season.",
    phrase: "\"The 405\" — locals say 'the' before freeway numbers, a Southern California tell.",
    pacing: "3-4 days",
    headsup: "Plan drives around rush hour; the 'gridlock from 7–10am and 3–7pm' is no exaggeration."
  },
  {
    id: "san-francisco-golden-gate",
    name: "San Francisco & the Golden Gate",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 37.77,
    lng: -122.42,
    blurb: "Fog rolls past a burnt-orange bridge while cable cars groan up impossible hills.",
    wiki: "https://en.wikipedia.org/wiki/Golden_Gate_Bridge",
    splurge: false,
    badge: null,
    eat: "Cioppino — a tomato seafood stew invented by the city's Italian fishermen",
    tip: "Layer up even in summer; the bay's afternoon fog and wind turn July genuinely cold.",
    dont: "Don't call it 'Frisco' or 'San Fran'; longtime residents wince at both nicknames.",
    bestTime: "September–October, the city's warmest, clearest stretch after the foggy summer.",
    phrase: "\"Hella\" — Bay Area slang meaning very or a lot, as in 'hella good'.",
    pacing: "2-3 days",
    headsup: "Don't leave anything visible in a parked car; smash-and-grab break-ins are rampant, even in daylight."
  },
  {
    id: "las-vegas-grand-canyon",
    name: "Las Vegas & the Grand Canyon",
    region: "North America",
    country: "United States",
    type: "Natural",
    weekends: 1,
    costUSD: 700,
    lat: 36.11,
    lng: -112.11,
    blurb: "Neon excess by night, then a mile-deep gorge glowing red as the desert sun lifts.",
    wiki: "https://en.wikipedia.org/wiki/Grand_Canyon",
    splurge: false,
    badge: "natural7",
    eat: "Shrimp cocktail — the old-school 99-cent Vegas casino classic in a tulip glass",
    tip: "Hit the canyon's South Rim at sunrise or sunset; midday flattens the colors and bakes you.",
    dont: "Don't try to hike to the river and back in one day; rangers rescue dehydrated tourists who do.",
    bestTime: "April–May or September–October; summer canyon heat and crowds are punishing.",
    phrase: "\"Comp\" — a casino freebie (room, drink, meal) earned by playing.",
    pacing: "3-4 days",
    headsup: "It's a 4.5-hour drive each way from the Strip to the South Rim; don't underestimate the distance."
  },
  {
    id: "utah-parks-zion-bryce-antelope",
    name: "Utah parks — Zion, Bryce & Antelope Canyon",
    region: "North America",
    country: "United States",
    type: "Natural",
    weekends: 1,
    costUSD: 700,
    lat: 37.30,
    lng: -113.03,
    blurb: "Wade a slot river in Zion, then watch dawn ignite Bryce's army of orange spires.",
    wiki: "https://en.wikipedia.org/wiki/Zion_National_Park",
    splurge: false,
    badge: null,
    eat: "Navajo fry bread taco — puffed fried dough piled with beans, beef and cheese",
    tip: "Zion's main canyon is shuttle-only most of the year; cars aren't allowed up Scenic Drive.",
    dont: "Don't visit Antelope Canyon alone; it's Navajo land and entry requires a booked tribal guide.",
    bestTime: "April–May or September–October; summer brings heat and flash-flood season in the slots.",
    phrase: "\"Yá'át'ééh\" (yah-ah-teh) — Navajo greeting meaning hello / it is good.",
    pacing: "4-5 days",
    headsup: "The Narrows and slot canyons flash-flood fast; check the forecast and never enter under storm threat."
  },
  {
    id: "yosemite-half-dome",
    name: "Yosemite — Half Dome",
    region: "North America",
    country: "United States",
    type: "Natural",
    weekends: 1,
    costUSD: 700,
    lat: 37.75,
    lng: -119.53,
    blurb: "Granite walls plunge to a green valley where waterfalls leap thousands of feet.",
    wiki: "https://en.wikipedia.org/wiki/Yosemite_National_Park",
    splurge: false,
    badge: null,
    eat: "Sourdough — Gold Rush–era California bread with its signature tangy crust",
    tip: "Drive up to Glacier Point for the classic Half Dome panorama without the brutal cable climb.",
    dont: "Don't store food in your car or tent; bears break in for it, so use the metal bear lockers.",
    bestTime: "May–June for thundering waterfalls; many high roads close under snow in winter.",
    phrase: "\"Trailhead\" — the marked start of a hiking trail, US park parlance.",
    pacing: "3-4 days",
    headsup: "Half Dome cables need a permit won by lottery months ahead, and park entry now needs a timed reservation in peak season."
  },
  {
    id: "yellowstone-grand-teton",
    name: "Yellowstone & Grand Teton",
    region: "North America",
    country: "United States",
    type: "Natural",
    weekends: 1,
    costUSD: 700,
    lat: 44.43,
    lng: -110.59,
    blurb: "Geysers erupt over a supervolcano while bison graze beneath the jagged Teton peaks.",
    wiki: "https://en.wikipedia.org/wiki/Yellowstone_National_Park",
    splurge: false,
    badge: null,
    eat: "Bison burger — lean, slightly sweet grass-fed buffalo, a Mountain West staple",
    tip: "Old Faithful's next eruption is posted at the visitor center; time your loop around it.",
    dont: "Don't step off the boardwalks near hot springs; the thin crust hides scalding water and has killed people.",
    bestTime: "June–September; most roads close from November to spring under deep snow.",
    phrase: "\"Bear spray\" — the pepper deterrent locals carry on every backcountry hike.",
    pacing: "4-5 days",
    headsup: "Stay 100 yards from bears and wolves and 25 from bison; gored 'selfie' tourists make news every year."
  },
  {
    id: "mount-rushmore",
    name: "Mount Rushmore",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 43.88,
    lng: -103.46,
    blurb: "Four presidents sixty feet tall, carved straight into the Black Hills granite.",
    wiki: "https://en.wikipedia.org/wiki/Mount_Rushmore",
    splurge: false,
    badge: null,
    eat: "Indian taco / bison stew — Black Hills fare on fry bread with Plains bison",
    tip: "Entry is free but you pay to park; arrive for the evening lighting ceremony in summer.",
    dont: "Don't skip the nearby Crazy Horse Memorial; ignoring the Lakota counterpoint misses the fuller story.",
    bestTime: "May–September; the surrounding roads and lighting ceremony pause in winter.",
    phrase: "\"The Hills\" — locals' name for the forested Black Hills around the monument.",
    pacing: "1-2 days",
    headsup: "It's remote; Rapid City is the nearest airport and you'll need a rental car to reach it."
  },
  {
    id: "new-orleans",
    name: "New Orleans",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 29.95,
    lng: -90.07,
    blurb: "Brass bands spill from wrought-iron balconies into streets thick with Creole spice.",
    wiki: "https://en.wikipedia.org/wiki/New_Orleans",
    splurge: false,
    badge: null,
    eat: "Gumbo — a dark-roux Creole stew of okra, the 'holy trinity' and seafood or sausage",
    tip: "You can legally carry a drink on the street in a plastic 'go-cup', but glass is banned.",
    dont: "Don't grab beads off a Mardi Gras float; wait for them to be thrown, snatching is rude.",
    bestTime: "February–May for Mardi Gras and Jazz Fest, before summer's swampy heat.",
    phrase: "\"Lagniappe\" (lan-yap) — a little something extra given for free.",
    pacing: "3-4 days",
    headsup: "Bourbon Street gets sketchy late; stick to lit main streets and watch your wallet in the Quarter crowds."
  },
  {
    id: "miami-florida-keys",
    name: "Miami & the Florida Keys",
    region: "North America",
    country: "United States",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 25.76,
    lng: -80.19,
    blurb: "Pastel Art Deco, Cuban espresso, and a highway hopping turquoise islands to Key West.",
    wiki: "https://en.wikipedia.org/wiki/Miami",
    splurge: false,
    badge: null,
    eat: "Cuban sandwich — pressed ham, roast pork, Swiss, pickles and mustard on Cuban bread",
    tip: "Order a 'cafecito' or 'colada' at a Little Havana ventanita window and share it like locals.",
    dont: "Don't only speak English in Little Havana; a bit of Spanish opens doors and warms the welcome.",
    bestTime: "November–April for dry warmth; summer is humid hurricane season.",
    phrase: "\"Dale\" (dah-leh) — Miami Cuban slang for okay / go for it / let's do this.",
    pacing: "4-5 days (with the Keys)",
    headsup: "South Beach restaurants often auto-add an 18–20% gratuity to the bill, so check before tipping again."
  },
  {
    id: "mexico-city-teotihuacan",
    name: "Mexico City & Teotihuacán",
    region: "North America",
    country: "Mexico",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 19.43,
    lng: -99.13,
    blurb: "An Aztec capital reborn as a megacity, crowned by pyramids on the Avenue of the Dead.",
    wiki: "https://en.wikipedia.org/wiki/Teotihuacan",
    splurge: false,
    badge: null,
    eat: "Tacos al pastor — spit-roasted marinated pork shaved off with a slice of pineapple",
    tip: "Visit Teotihuacán's pyramids at opening before the heat and tour buses arrive.",
    dont: "Don't drink tap water; locals don't either, stick to bottled or purified water.",
    bestTime: "March–May for warm dry days; June–September brings afternoon rains.",
    phrase: "\"¿Mande?\" (man-deh) — polite Mexican way to say 'pardon, what did you say?'",
    pacing: "3-4 days",
    headsup: "The city sits at 2,240m; altitude can leave you breathless the first day, so ease in and hydrate."
  },
  {
    id: "chichen-itza-tulum-yucatan",
    name: "Chichén Itzá, Tulum & the Yucatán",
    region: "North America",
    country: "Mexico",
    type: "Wonder",
    weekends: 1,
    costUSD: 700,
    lat: 20.68,
    lng: -88.57,
    blurb: "A Maya pyramid casts a serpent of shadow while cenotes glow turquoise underground.",
    wiki: "https://en.wikipedia.org/wiki/Chichen_Itza",
    splurge: false,
    badge: "new7",
    eat: "Cochinita pibil — achiote-marinated pork slow-roasted in banana leaves, a Yucatán specialty",
    tip: "You can no longer climb El Castillo; admire and photograph it from the ground only.",
    dont: "Don't wear sunscreen before swimming in a cenote; the chemicals harm the fragile freshwater life.",
    bestTime: "November–April dry season; come at the equinox for the famous serpent-shadow effect.",
    phrase: "\"Bix a beel?\" (beesh-ah-bell) — Yucatec Maya for 'how are you?'",
    pacing: "4-5 days",
    headsup: "Arrive at Chichén Itzá at opening; by mid-morning vendor stalls and tour crowds swarm the site."
  },
  {
    id: "oaxaca-dia-de-muertos",
    name: "Oaxaca — Día de Muertos",
    region: "North America",
    country: "Mexico",
    type: "Experience",
    weekends: 1,
    costUSD: 700,
    lat: 17.07,
    lng: -96.72,
    blurb: "Marigold-lit altars and candlelit graveyards welcome the dead back for one bright night.",
    wiki: "https://en.wikipedia.org/wiki/Day_of_the_Dead",
    splurge: false,
    badge: null,
    eat: "Mole negro — a deep, complex Oaxacan sauce of chiles, chocolate and dozens of spices",
    tip: "Sip mezcal the local way, neat with orange slices and sal de gusano, not as a shot.",
    dont: "Don't treat cemetery vigils as a photo backdrop; ask before shooting and respect grieving families.",
    bestTime: "Late October–November 2 for Día de Muertos; book lodging months ahead.",
    phrase: "\"Provecho\" — said to others who are eating, like 'enjoy your meal'.",
    pacing: "4-5 days",
    headsup: "Día de Muertos lodging sells out and prices spike; reserve well in advance and carry cash for markets."
  },
  {
    id: "havana",
    name: "Havana",
    region: "North America",
    country: "Cuba",
    type: "City",
    weekends: 1,
    costUSD: 700,
    lat: 23.13,
    lng: -82.38,
    blurb: "Fifties Chevrolets cruise crumbling colonial facades as son drifts from open doorways.",
    wiki: "https://en.wikipedia.org/wiki/Havana",
    splurge: false,
    badge: null,
    eat: "Ropa vieja — shredded beef braised in tomato, peppers and wine, Cuba's national dish",
    tip: "Stay in a 'casa particular' family guesthouse; it's the warmest, most authentic way to lodge.",
    dont: "Don't expect to pay by foreign card; US-issued cards rarely work, so plan around cash.",
    bestTime: "November–April dry season; summers are hot and hurricane-prone.",
    phrase: "\"Asere, ¿qué bolá?\" (ah-seh-reh keh boh-LAH) — Cuban slang for 'hey buddy, what's up?'",
    pacing: "3-4 days",
    headsup: "Bring enough cash for the whole trip; ATMs are unreliable, and convert euros, which beat dollars here."
  },
  {
    id: "banff-canadian-rockies",
    name: "Banff & the Canadian Rockies",
    region: "North America",
    country: "Canada",
    type: "Natural",
    weekends: 2,
    costUSD: 1400,
    lat: 51.18,
    lng: -115.57,
    blurb: "Glacier-fed lakes glow impossible turquoise beneath sawtooth peaks and hanging icefields.",
    wiki: "https://en.wikipedia.org/wiki/Banff_National_Park",
    splurge: false,
    badge: null,
    eat: "Poutine — fries smothered in cheese curds and gravy, a Canadian comfort classic",
    tip: "Lake Louise and Moraine Lake fill by dawn; take the shuttle since private cars are restricted.",
    dont: "Don't approach elk or feed any wildlife; rutting elk charge and fed animals get euthanized.",
    bestTime: "June–September for ice-free lakes and open Icefields Parkway; that turquoise needs sunlight.",
    phrase: "\"Loonie / Toonie\" — the one- and two-dollar Canadian coins.",
    pacing: "5-7 days",
    headsup: "You need a Parks Canada pass displayed on the dash; rangers ticket cars without one at trailheads."
  },
  {
    id: "pacific-coast-highway-big-sur",
    name: "Pacific Coast Highway & Big Sur",
    region: "North America",
    country: "United States",
    type: "RoadTrip",
    weekends: 2,
    costUSD: 1400,
    lat: 36.27,
    lng: -121.81,
    blurb: "A cliff-hugging ribbon of asphalt where redwoods meet the crashing Pacific surf.",
    wiki: "https://en.wikipedia.org/wiki/Big_Sur",
    splurge: false,
    badge: null,
    eat: "Cioppino & Monterey calamari — fresh-caught seafood along the central California coast",
    tip: "Drive south (north-to-south) so you're on the ocean side for the cliff-edge views and pullouts.",
    dont: "Don't bank on a quick trip; landslides periodically close stretches of Highway 1, so check conditions.",
    bestTime: "September–October for clear skies; summer mornings drown the coast in fog.",
    phrase: "\"Gnarly\" — California surf slang for intense, in a good or hairy way.",
    pacing: "4-6 days",
    headsup: "Gas stations and cell signal are sparse through Big Sur; fuel up and download maps before the cliffs."
  },
  {
    id: "hawaii-multi-island",
    name: "Hawaii — multi-island",
    region: "North America",
    country: "United States",
    type: "Island",
    weekends: 2,
    costUSD: 1400,
    lat: 20.80,
    lng: -156.33,
    blurb: "Black-sand beaches, green sea cliffs, and lava glowing red where new land is born.",
    wiki: "https://en.wikipedia.org/wiki/Hawaii",
    splurge: false,
    badge: null,
    eat: "Poke bowl — cubed raw ahi tuna with soy, sesame and seaweed over rice",
    tip: "Use reef-safe sunscreen; oxybenzone sunscreens are banned in Hawaii to protect the coral.",
    dont: "Don't take lava rocks or sand home; locals consider it disrespectful to Pele and bad luck.",
    bestTime: "April–May or September–October dodge crowds and peak prices; weather is good year-round.",
    phrase: "\"Aloha\" — hello, goodbye and love; \"Mahalo\" — thank you.",
    pacing: "10-14 days",
    headsup: "Inter-island flights are essential to combine islands; book them and rental cars early as they sell out."
  },
  {
    id: "alaska-denali-aurora",
    name: "Alaska — Denali & aurora",
    region: "North America",
    country: "United States",
    type: "Natural",
    weekends: 2,
    costUSD: 1400,
    lat: 63.07,
    lng: -151.01,
    blurb: "North America's highest peak towers over tundra where green auroras ripple overhead.",
    wiki: "https://en.wikipedia.org/wiki/Denali",
    splurge: false,
    badge: null,
    eat: "Wild Alaskan salmon — fresh-caught sockeye or king, often cedar-planked or smoked",
    tip: "Private cars go only 15 miles into Denali; take the park bus deep for wildlife and the peak.",
    dont: "Don't count on seeing the summit; Denali makes its own weather and hides in cloud most days.",
    bestTime: "June–August for Denali wildlife; late August–April nights for the aurora.",
    phrase: "\"Outside\" — what Alaskans call the rest of the continental US.",
    pacing: "7-10 days",
    headsup: "Aurora and clear-peak views are weather lotteries; budget extra nights to improve your odds."
  },
  {
    id: "route-66-chicago-to-la",
    name: "Route 66 — Chicago to LA",
    region: "North America",
    country: "United States",
    type: "RoadTrip",
    weekends: 4,
    costUSD: 2800,
    lat: 35.20,
    lng: -101.83,
    blurb: "2,400 miles of neon motels, ghost towns and diners along America's mother road.",
    wiki: "https://en.wikipedia.org/wiki/Route_66",
    splurge: false,
    badge: null,
    eat: "Route 66 diner pie & chili — roadside Americana from Springfield to Amarillo",
    tip: "Follow the brown 'Historic Route 66' signs and old alignments; the interstate bypassed the best bits.",
    dont: "Don't try to do it in a week; rushing past the kitschy stops misses the entire point of the road.",
    bestTime: "May or September–October; avoid desert summer heat and winter mountain snow.",
    phrase: "\"Get your kicks on Route 66\" — the road's anthem and unofficial motto.",
    pacing: "2-3 weeks",
    headsup: "Long stretches through the Southwest have little fuel, water or signal; carry extra water and a paper map."
  },
];
