// Oceania — World Bucket List data (auto-generated, hand-tuned facts)
window.WBL_OCEANIA = [
  {
    id: "sydney-opera-house-bridgeclimb",
    name: "Sydney — Opera House & BridgeClimb",
    region: "Oceania",
    country: "Australia",
    type: "City",
    weekends: 1,
    costUSD: 1300,
    lat: -33.86,
    lng: 151.21,
    blurb: "Climb the steel arch at dawn, then catch an opera under those famous white sails.",
    wiki: "https://en.wikipedia.org/wiki/Sydney_Opera_House",
    splurge: false,
    badge: null,
    eat: "Sydney rock oysters — small, briny, mineral-sharp oysters slurped raw with a squeeze of lemon",
    tip: "Tap on AND off with a contactless card or phone on Opal readers for trains, ferries and buses; no paper ticket needed.",
    dont: "Don't bring your own camera or phone on the BridgeClimb — loose items are banned for safety and confiscated at the start.",
    bestTime: "September to November (spring) — warm, dry, jacaranda in bloom, before summer crowds.",
    phrase: "Arvo — Aussie slang for afternoon, as in 'see you this arvo'",
    pacing: "3-4 days",
    headsup: "BridgeClimb and Opera House performances sell out weeks ahead in summer and on weekends — book online before you fly in.",
  },
  {
    id: "uluru-red-centre",
    name: "Uluru & the Red Centre",
    region: "Oceania",
    country: "Australia",
    type: "Natural",
    weekends: 1,
    costUSD: 1000,
    lat: -25.34,
    lng: 131.04,
    blurb: "A single colossal sandstone monolith flares blood-red as the desert sun drops.",
    wiki: "https://en.wikipedia.org/wiki/Uluru",
    splurge: false,
    badge: null,
    eat: "Kangaroo fillet with native pepperberry and quandong — lean game meat with tart desert-fruit notes at the Field of Light dinner",
    tip: "Walk the full base loop (about 10 km) rather than just photographing from the car park — the rock's caves and waterholes only reveal themselves up close.",
    dont: "Don't climb Uluru — the climb was permanently banned in 2019 at the request of the Anangu, its traditional owners, for whom it is sacred.",
    bestTime: "May to September — cool days suited to walking; summer afternoons top 40C.",
    phrase: "Palya (pal-ya) — hello/good in Pitjantjatjara, the local Anangu language",
    pacing: "2-3 days",
    headsup: "There is no town at Uluru, only the Yulara resort village, and prices are steep — fuel up and stock snacks before the long drive in.",
  },
  {
    id: "great-ocean-road",
    name: "Great Ocean Road",
    region: "Oceania",
    country: "Australia",
    type: "RoadTrip",
    weekends: 1,
    costUSD: 1000,
    lat: -38.66,
    lng: 143.10,
    blurb: "Cliff-hugging tarmac unspools past limestone stacks rising straight from a wild southern sea.",
    wiki: "https://en.wikipedia.org/wiki/Great_Ocean_Road",
    splurge: false,
    badge: null,
    eat: "Apollo Bay scallops, fresh off the boat and seared simply — the town hosts a seafood festival each summer",
    tip: "Drive west from Torquay so the ocean is on your left and pull-offs are an easy left turn straight into the lookouts.",
    dont: "Don't try to do the whole road as a single-day round trip from Melbourne — the winding coast is exhausting and you will only glimpse the Twelve Apostles in fading light.",
    bestTime: "March to May (autumn) — calm, clear roads and fewer summer holiday convoys.",
    phrase: "Roo — Aussie slang for kangaroo; watch for them at dusk on this stretch",
    pacing: "2-3 days",
    headsup: "Phone signal vanishes for long stretches in the Otway forest, and koalas and kangaroos cross the road at dawn and dusk — slow right down.",
  },
  {
    id: "melbourne",
    name: "Melbourne",
    region: "Oceania",
    country: "Australia",
    type: "City",
    weekends: 1,
    costUSD: 1000,
    lat: -37.81,
    lng: 144.96,
    blurb: "Graffiti laneways, third-wave espresso and rooftop bars stack up in Australia's coffee capital.",
    wiki: "https://en.wikipedia.org/wiki/Melbourne",
    splurge: false,
    badge: null,
    eat: "A flat white — espresso under a thin layer of steamed microfoam, the drink Melbourne built its coffee reputation on",
    tip: "Trams are free inside the central Free Tram Zone, but tap your Myki card the moment you ride beyond it or you risk a fine.",
    dont: "Don't order a 'latte' expecting a flat white, and never call drip filter coffee a real coffee in a Melbourne cafe — baristas take their craft seriously.",
    bestTime: "February to March — warm, dry and the festival and tennis season; pack layers for 'four seasons in a day'.",
    phrase: "Parma — local slang for a chicken parmigiana, a pub staple",
    pacing: "3-4 days",
    headsup: "Melbourne's weather genuinely swings 15C in an hour — locals carry a jacket even on hot mornings, and so should you.",
  },
  {
    id: "fiji",
    name: "Fiji",
    region: "Oceania",
    country: "Fiji",
    type: "Island",
    weekends: 1,
    costUSD: 1000,
    lat: -17.71,
    lng: 178.07,
    blurb: "Soft white sand, glassy lagoons and a village welcome warmer than the tropical sun.",
    wiki: "https://en.wikipedia.org/wiki/Fiji",
    splurge: false,
    badge: null,
    eat: "Kokoda — raw walu fish 'cooked' in lime juice with coconut cream, chilli and onion, served in a coconut shell",
    tip: "If invited to a kava ceremony, clap once before accepting the bowl, drink it in one go, then clap three times and say 'maca'.",
    dont: "Don't wear a hat or sunglasses or touch anyone's head when visiting a Fijian village — it's seen as disrespectful to the chief and elders.",
    bestTime: "May to October — the dry season, with lower humidity and less cyclone risk.",
    phrase: "Bula (boo-lah) — hello and a wish for life and health, used constantly",
    pacing: "5-7 days",
    headsup: "Most of the postcard scenery is on the outer Mamanuca and Yasawa islands — budget for a catamaran transfer, as the main island's coast is mostly mangrove.",
  },
  {
    id: "bora-bora-tahiti",
    name: "Bora Bora & Tahiti",
    region: "Oceania",
    country: "French Polynesia",
    type: "Island",
    weekends: 1,
    costUSD: 1000,
    lat: -16.50,
    lng: -151.74,
    blurb: "Overwater bungalows float on a turquoise lagoon ringed by jagged volcanic peaks.",
    wiki: "https://en.wikipedia.org/wiki/Bora_Bora",
    splurge: false,
    badge: null,
    eat: "Poisson cru — tuna marinated in lime and bathed in fresh coconut milk, the Tahitian national dish",
    tip: "Bring a tiare flower tucked behind your ear — worn over the left it signals you're taken, over the right that you're available.",
    dont: "Don't expect to pay in dollars or euros — French Polynesia uses the CFP franc, and many smaller vendors and pensions are cash-only.",
    bestTime: "May to October — the cooler, drier austral winter with calm lagoon water.",
    phrase: "Ia ora na (yo-rah-nah) — hello/good day in Tahitian",
    pacing: "5-7 days",
    headsup: "Flights from Tahiti to Bora Bora are short but pricey and book out fast around French school holidays — reserve the inter-island Air Tahiti leg early.",
  },
  {
    id: "tasmania",
    name: "Tasmania",
    region: "Oceania",
    country: "Australia",
    type: "Natural",
    weekends: 1,
    costUSD: 1000,
    lat: -41.45,
    lng: 145.96,
    blurb: "Ancient rainforest, jagged dolerite peaks and the cleanest air on Earth, all on one wild island.",
    wiki: "https://en.wikipedia.org/wiki/Tasmania",
    splurge: false,
    badge: null,
    eat: "Tasmanian oysters and a tasting flight of cool-climate Pinot Noir from the Tamar Valley vineyards",
    tip: "Book a MONA visit and arrive by the museum's own catamaran ferry from Hobart's waterfront — the camo-painted boat is part of the experience.",
    dont: "Don't drive the back roads at night if you can avoid it — Tasmania has horrific roadkill rates and wallabies, wombats and devils dart out constantly.",
    bestTime: "December to February (summer) — the only reliably warm, dry window for the Overland Track and highland walks.",
    phrase: "Cuppa — a cup of tea, often the centre of any Tassie catch-up",
    pacing: "7-10 days",
    headsup: "The Overland Track requires a booked permit and a fee in the October-to-May peak season, and numbers are capped daily — reserve months ahead.",
  },
  {
    id: "great-barrier-reef-cairns-whitsundays",
    name: "Great Barrier Reef & Cairns — PADI dive & Whitsundays",
    region: "Oceania",
    country: "Australia",
    type: "Experience",
    weekends: 2,
    costUSD: 3200,
    lat: -16.92,
    lng: 145.78,
    blurb: "Earn your dive ticket over the world's largest living reef, then sail to silica-white Whitehaven Beach.",
    wiki: "https://en.wikipedia.org/wiki/Great_Barrier_Reef",
    splurge: true,
    badge: null,
    eat: "Barramundi grilled with native finger lime and macadamia — a flaky local fish caught off the tropical north coast",
    tip: "Wear a full-body stinger suit on every reef trip — operators supply them, and they protect against both jellyfish and the fierce tropical sun.",
    dont: "Don't touch or stand on the coral, even with fins — contact kills the living polyps, and rangers and operators enforce strict no-touch rules.",
    bestTime: "June to October — dry season with the best underwater visibility and minimal box-jellyfish risk.",
    phrase: "She'll be right — Aussie reassurance meaning 'it'll all work out fine'",
    pacing: "7-10 days",
    headsup: "Allow a clear 18-24 hours between your last scuba dive and any flight — the altitude can trigger decompression sickness, so plan your departure carefully.",
  },
  {
    id: "australian-outback-kakadu",
    name: "Australian Outback & Kakadu",
    region: "Oceania",
    country: "Australia",
    type: "Natural",
    weekends: 2,
    costUSD: 2000,
    lat: -12.84,
    lng: 132.83,
    blurb: "Plunge pools, thundering wet-season falls and 20,000-year-old rock art across a vast tropical wilderness.",
    wiki: "https://en.wikipedia.org/wiki/Kakadu_National_Park",
    splurge: false,
    badge: null,
    eat: "Magpie goose, a fatty wild fowl traditionally hunted by Bininj people, served at some Aboriginal-guided tours",
    tip: "Hire a guide from the Bininj/Mungguy traditional owners to read the Ubirr and Nourlangie rock-art galleries — the stories make the paintings come alive.",
    dont: "Don't swim or stand at the water's edge anywhere except signposted plunge pools — saltwater crocodiles inhabit nearly every river and billabong here.",
    bestTime: "May to September (the dry) — roads and waterfalls are accessible; the wet season floods most tracks.",
    phrase: "Bobo (bo-bo) — goodbye in the local Kunwinjku language",
    pacing: "5-7 days",
    headsup: "Many of Kakadu's best gorges and falls need a high-clearance 4WD and are cut off entirely in the wet season — check Parks road reports before setting out.",
  },
  {
    id: "nz-north-island-rotorua-hobbiton-tongariro",
    name: "NZ North Island — Rotorua, Hobbiton & Tongariro",
    region: "Oceania",
    country: "New Zealand",
    type: "Natural",
    weekends: 2,
    costUSD: 2000,
    lat: -38.14,
    lng: 176.25,
    blurb: "Steaming geysers, a real-life Shire and a volcanic alpine crossing past emerald crater lakes.",
    wiki: "https://en.wikipedia.org/wiki/Rotorua",
    splurge: false,
    badge: null,
    eat: "Hangi — meat and root vegetables slow-steamed in an earth oven over hot stones, served at Maori cultural evenings",
    tip: "At a marae welcome, press noses and foreheads together in the hongi to share breath — return the greeting rather than offering a handshake.",
    dont: "Don't sit on tables or pass food over someone's head in Maori settings — food and the body's tapu (sacredness) must never mix.",
    bestTime: "December to March — warm, settled weather for the exposed Tongariro Alpine Crossing.",
    phrase: "Kia ora (kee-ah or-ah) — hello, thanks, and good wishes all in one",
    pacing: "6-8 days",
    headsup: "The Tongariro Alpine Crossing is a one-way 19.4 km track — you must pre-book a shuttle to return to your car, and weather closes it without warning.",
  },
  {
    id: "nz-south-island-queenstown-milford-aoraki",
    name: "NZ South Island — Queenstown, Milford & Aoraki",
    region: "Oceania",
    country: "New Zealand",
    type: "Trek",
    weekends: 3,
    costUSD: 3200,
    lat: -45.03,
    lng: 168.66,
    blurb: "Bungy birthplace, a fiord of vertical waterfalls and the snow crown of New Zealand's highest peak.",
    wiki: "https://en.wikipedia.org/wiki/Queenstown,_New_Zealand",
    splurge: false,
    badge: null,
    eat: "Fergburger — Queenstown's legendary made-to-order burger with queues snaking down the street day and night",
    tip: "Drive to Milford Sound the night before from Te Anau and start early — the road is long, gated by avalanche risk, and the morning light is best.",
    dont: "Don't underestimate the sandflies at Milford Sound — they swarm relentlessly, so bring strong repellent or you'll be eaten alive at the viewpoints.",
    bestTime: "December to February for the Great Walks; June to August if you want the ski fields above Queenstown.",
    phrase: "Sweet as — Kiwi slang for 'great' or 'no worries'",
    pacing: "10-14 days",
    headsup: "The Milford, Routeburn and Kepler Great Walk huts open for booking months ahead and sell out within minutes — secure beds the day reservations open.",
  },
];
