// South America — World Bucket List data (auto-generated, hand-tuned facts)
window.WBL_SOUTH_AMERICA = [
  {
    id: "rio-christ-redeemer-carnival",
    name: "Rio de Janeiro — Christ the Redeemer & Carnival",
    region: "South America",
    country: "Brazil",
    type: "Wonder",
    weekends: 1,
    costUSD: 900,
    lat: -22.95,
    lng: -43.21,
    blurb: "Samba thunders, beaches glitter, and a stone Christ holds the whole shimmering bay in his arms.",
    wiki: "https://en.wikipedia.org/wiki/Christ_the_Redeemer",
    splurge: false,
    badge: "new7",
    eat: "Feijoada — slow black-bean stew with smoked pork, eaten on Saturdays with orange and farofa.",
    tip: "Greet with a kiss on alternate cheeks (one in Rio, never a stiff handshake among friends), and run on relaxed time.",
    dont: "Don't flash your phone or wear a wristwatch on the beach or in crowds — petty theft on Copacabana is constant.",
    bestTime: "December to March for sun and Carnival (peaking around Feb/March); book Carnival lodging a year ahead.",
    phrase: "Tudo bem? (too-doo beng) — All good? / used as both hello and how are you.",
    pacing: "4-5 days",
    headsup: "Buy timed Cristo Redentor van or train tickets online in advance; clouds often swallow the statue by midday, so go early."
  },
  {
    id: "iguazu-falls",
    name: "Iguazú Falls",
    region: "South America",
    country: "Argentina",
    type: "Natural",
    weekends: 1,
    costUSD: 900,
    lat: -25.69,
    lng: -54.44,
    blurb: "Two hundred and seventy waterfalls roar through the jungle, drenching you at the Devil's Throat catwalk.",
    wiki: "https://en.wikipedia.org/wiki/Iguazu_Falls",
    splurge: false,
    badge: null,
    eat: "Chipá — warm, chewy cassava-and-cheese rolls sold hot at the park and roadside stalls.",
    tip: "Do both sides — the Argentine park for up-close walkways, the Brazilian side for the sweeping panorama — and carry both currencies.",
    dont: "Don't feed or photograph the coatis up close; they bite and swarm anyone holding food on the trails.",
    bestTime: "March to May or September to November — high water yet fewer crowds and gentler heat than summer.",
    phrase: "¿La Garganta del Diablo? (lah gar-GAN-tah del dee-AH-blo) — Where's the Devil's Throat?",
    pacing: "2 days",
    headsup: "You need a passport to cross between the Argentine and Brazilian parks; check visa rules before planning to see both."
  },
  {
    id: "buenos-aires",
    name: "Buenos Aires",
    region: "South America",
    country: "Argentina",
    type: "City",
    weekends: 1,
    costUSD: 900,
    lat: -34.61,
    lng: -58.38,
    blurb: "Tango spills from milongas at midnight while steakhouses sizzle and bookshops fill old opera houses.",
    wiki: "https://en.wikipedia.org/wiki/Buenos_Aires",
    splurge: false,
    badge: null,
    eat: "Bife de chorizo with chimichurri — thick sirloin grilled at an asado, washed down with Malbec.",
    tip: "Bring crisp US dollars and change them at the informal 'blue' rate via a cueva — far better than card or official rates.",
    dont: "Don't show up for dinner at 7pm; porteños eat at 10pm and a milonga only warms up after midnight.",
    bestTime: "Spring (October-November) or autumn (March-April) for mild weather and jacaranda blossoms.",
    phrase: "Che, ¿todo bien? (cheh, TOH-doh bee-EN) — Hey, all good? / 'che' is the classic Argentine filler.",
    pacing: "4-5 days",
    headsup: "Avoid hailing street taxis with cash; use Cabify or a radio taxi, as some metered cabs rig fares or swap notes."
  },
  {
    id: "lima",
    name: "Lima",
    region: "South America",
    country: "Peru",
    type: "City",
    weekends: 1,
    costUSD: 900,
    lat: -12.05,
    lng: -77.04,
    blurb: "Cliff-top neighborhoods overlook the Pacific while the world's best kitchens reinvent Peru on a plate.",
    wiki: "https://en.wikipedia.org/wiki/Lima",
    splurge: false,
    badge: null,
    eat: "Ceviche — raw fish cured in lime 'leche de tigre' with chili, red onion and sweet potato, eaten at lunch.",
    tip: "Eat ceviche before mid-afternoon — locals consider evening ceviche a sign of un-fresh fish.",
    dont: "Don't call the local sour 'just a margarita' — pisco sour is national pride, and Peruvians fiercely dispute Chile's claim to pisco.",
    bestTime: "December to April for sun; May to November brings the grey coastal fog locals call la garúa.",
    phrase: "¿Cuánto cuesta? (KWAN-toh KWES-tah) — How much is it?",
    pacing: "2-3 days",
    headsup: "Stay in Miraflores or Barranco; tap water is not drinkable, so stick to bottled even for brushing teeth."
  },
  {
    id: "cusco-sacred-valley-machu-picchu",
    name: "Cusco, Sacred Valley & Machu Picchu",
    region: "South America",
    country: "Peru",
    type: "Wonder",
    weekends: 1,
    costUSD: 900,
    lat: -13.16,
    lng: -72.55,
    blurb: "Mist parts over terraced ruins clinging to a green Andean spine the Inca somehow built without mortar.",
    wiki: "https://en.wikipedia.org/wiki/Machu_Picchu",
    splurge: false,
    badge: "new7",
    eat: "Cuy — whole roasted guinea pig, an Andean delicacy served at Cusco festivals and Sacred Valley markets.",
    tip: "Spend two days acclimatizing in the Sacred Valley (lower than Cusco) and sip coca tea before tackling altitude.",
    dont: "Don't bring drones or tripods to Machu Picchu, and don't try to re-enter on one ticket — circuits are one-way and timed.",
    bestTime: "May to September dry season; April or October dodge crowds with decent weather.",
    phrase: "Allillanchu (ah-yee-YAN-choo) — Hello / how are you, in Quechua.",
    pacing: "5-6 days",
    headsup: "Entry tickets are timed, capped daily and sell out weeks ahead in peak season — book the official site early plus your bus up."
  },
  {
    id: "inca-trail-machu-picchu",
    name: "Inca Trail to Machu Picchu",
    region: "South America",
    country: "Peru",
    type: "Trek",
    weekends: 1,
    costUSD: 1700,
    lat: -13.20,
    lng: -72.52,
    blurb: "Four days of stone stairways, cloud forest and high passes end at the Sun Gate dawn.",
    wiki: "https://en.wikipedia.org/wiki/Inca_Trail_to_Machu_Picchu",
    splurge: false,
    badge: null,
    eat: "Chicha morada — sweet purple-corn drink boiled with pineapple, cinnamon and clove that porters serve at camp.",
    tip: "Tip your porters and cook generously on the last night — they carry the camp and earn modest wages for brutal work.",
    dont: "Don't attempt it independently; the trail is permit-only through licensed agencies, and going off-route risks fines and rescue.",
    bestTime: "May to September dry season; the trail closes every February for maintenance.",
    phrase: "Sulpayki (sool-PIE-kee) — Thank you, in Quechua.",
    pacing: "4 days on trail, plus 2-3 to acclimatize",
    headsup: "Permits are strictly capped and routinely sell out 5-6 months ahead — book before buying flights, and the trek peaks near 4,200 m."
  },
  {
    id: "salar-de-uyuni",
    name: "Salar de Uyuni — the salt flats",
    region: "South America",
    country: "Bolivia",
    type: "Natural",
    weekends: 1,
    costUSD: 900,
    lat: -20.13,
    lng: -67.49,
    blurb: "The world's largest salt flat becomes a flawless sky-mirror, erasing the horizon after the rains.",
    wiki: "https://en.wikipedia.org/wiki/Salar_de_Uyuni",
    splurge: false,
    badge: null,
    eat: "Salteñas — juicy baked Bolivian empanadas with a sweet-spicy stew filling, eaten mid-morning in Uyuni town.",
    tip: "Book a multi-day 4x4 tour to also see the red Laguna Colorada and geysers; bring cash, as the region is remote and card-free.",
    dont: "Don't underestimate the cold or sun — nights drop below freezing and the salt's glare burns; pack sunglasses and a warm layer.",
    bestTime: "January to March for the mirror reflection; June to October for dry, drivable white hexagons.",
    phrase: "¿Cuánto cuesta el tour? (KWAN-toh KWES-tah el toor) — How much is the tour?",
    pacing: "3-4 days",
    headsup: "You sit above 3,600 m the whole time; altitude sickness is common, so acclimatize first and never drive the flats alone after rain."
  },
  {
    id: "la-paz-lake-titicaca",
    name: "La Paz & Lake Titicaca",
    region: "South America",
    country: "Bolivia",
    type: "City",
    weekends: 1,
    costUSD: 900,
    lat: -16.50,
    lng: -68.15,
    blurb: "Cable cars glide over a canyon city, then reed boats drift the highest navigable lake on Earth.",
    wiki: "https://en.wikipedia.org/wiki/La_Paz",
    splurge: false,
    badge: null,
    eat: "Anticuchos — skewered, marinated beef-heart grilled at La Paz street stalls with peanut sauce and potato.",
    tip: "Ride the Mi Teleférico cable-car network — it's the locals' metro and the cheapest aerial city tour anywhere.",
    dont: "Don't gawk or buy from the witches' market dried llama fetuses as mere curios; they're offerings to Pachamama, treated with respect.",
    bestTime: "May to October dry season; the altiplano sun is fierce but skies are clear over the lake.",
    phrase: "Kamisaraki (kah-mee-SAH-rah-kee) — How are you, in Aymara.",
    pacing: "3-4 days",
    headsup: "La Paz sits near 3,650 m and the airport in El Alto is higher still — arrive slow, skip alcohol day one, and chew coca leaves."
  },
  {
    id: "atacama-desert",
    name: "Atacama Desert",
    region: "South America",
    country: "Chile",
    type: "Natural",
    weekends: 1,
    costUSD: 900,
    lat: -23.46,
    lng: -67.39,
    blurb: "The driest place on Earth glows with steaming geysers, salt lagoons, and an unreal Milky Way overhead.",
    wiki: "https://en.wikipedia.org/wiki/Atacama_Desert",
    splurge: false,
    badge: null,
    eat: "Sopaipillas — fried pumpkin-dough flatbreads sold warm in San Pedro de Atacama, dipped in pebre salsa.",
    tip: "Base in San Pedro de Atacama and book an astronomy tour — the clear, high desert is one of the planet's best stargazing spots.",
    dont: "Don't skip layering: midday bakes, but dawn at the El Tatio geysers (4,300 m) is bitterly cold and the altitude bites.",
    bestTime: "Year-round, but March to May and September to November balance mild days with clearest night skies.",
    phrase: "Cachai? (kah-CHAI) — You get it? / quintessential Chilean slang.",
    pacing: "3-4 days",
    headsup: "Tours leave very early and the desert spans huge distances; rent a car or pre-book excursions, and carry cash for San Pedro."
  },
  {
    id: "cartagena",
    name: "Cartagena",
    region: "South America",
    country: "Colombia",
    type: "City",
    weekends: 1,
    costUSD: 900,
    lat: 10.42,
    lng: -75.55,
    blurb: "Bougainvillea spills over balconies in a walled Caribbean city of golden churches and breezy plazas.",
    wiki: "https://en.wikipedia.org/wiki/Cartagena,_Colombia",
    splurge: false,
    badge: null,
    eat: "Arepa de huevo — deep-fried cornmeal pocket with a whole egg inside, a Caribbean-coast breakfast.",
    tip: "Walk the old-city walls at sunset and agree the price before any horse-cart or vendor service — quotes balloon for tourists.",
    dont: "Don't accept 'free' bracelets, sunglasses or photos from beach palenqueras; they demand steep payment afterward.",
    bestTime: "December to April dry season; it's hot and humid year-round, so mornings and evenings are kindest.",
    phrase: "¿Qué más? (keh mahs) — What's up? / the standard Colombian greeting.",
    pacing: "3 days",
    headsup: "Street vendors and taxis run cash-only and rarely have change; carry small peso notes and negotiate cabs before getting in."
  },
  {
    id: "angel-falls",
    name: "Angel Falls",
    region: "South America",
    country: "Venezuela",
    type: "Natural",
    weekends: 1,
    costUSD: 900,
    lat: 5.97,
    lng: -62.54,
    blurb: "The world's tallest waterfall drops nearly a kilometre off a sheer tepui into the Lost World jungle.",
    wiki: "https://en.wikipedia.org/wiki/Angel_Falls",
    splurge: false,
    badge: null,
    eat: "Cachapa — sweet fresh-corn pancake folded over soft white queso de mano, a Venezuelan staple.",
    tip: "Reach it via Canaima lagoon by light plane plus a motorized dugout canoe; trips run as guided multi-day packages only.",
    dont: "Don't expect a full plunge in dry season — the falls can thin to a wisp, so time your visit for the rains.",
    bestTime: "June to November wet season, when the river is high enough for boats and the falls run full.",
    phrase: "¿Cómo está? (KOH-moh es-TAH) — How are you?",
    pacing: "3 days",
    headsup: "Venezuela's economy is volatile; bring US dollars cash, arrange everything through a reputable operator, and check current safety advisories."
  },
  {
    id: "easter-island-moai",
    name: "Easter Island — the Moai",
    region: "South America",
    country: "Chile",
    type: "Island",
    weekends: 1,
    costUSD: 900,
    lat: -27.11,
    lng: -109.35,
    blurb: "Hundreds of giant stone ancestors stand watch over the loneliest inhabited speck in the Pacific.",
    wiki: "https://en.wikipedia.org/wiki/Easter_Island",
    splurge: false,
    badge: null,
    eat: "Tunu ahi — fish grilled over hot volcanic stones in the traditional Rapa Nui umu earth-oven style.",
    tip: "Buy the national-park ticket on arrival and hire a Rapa Nui guide — many sacred ahu can only be visited with one.",
    dont: "Don't touch, climb on, or walk on the moai or their stone platforms; they're sacred ancestors and strictly protected.",
    bestTime: "October to April for warm weather; the Tapati festival in early February is the cultural highlight.",
    phrase: "Iorana (yoh-RAH-nah) — Hello, in the Rapa Nui language.",
    pacing: "3-4 days",
    headsup: "It's a 5-6 hour flight from Santiago with limited seats and pricey, scarce supplies — book flights and lodging well ahead and bring cash."
  },
  {
    id: "quito",
    name: "Quito",
    region: "South America",
    country: "Ecuador",
    type: "City",
    weekends: 1,
    costUSD: 900,
    lat: -0.22,
    lng: -78.51,
    blurb: "A perfectly preserved colonial old town glitters with gilded churches beneath a ring of Andean volcanoes.",
    wiki: "https://en.wikipedia.org/wiki/Quito",
    splurge: false,
    badge: null,
    eat: "Locro de papa — creamy Andean potato soup with cheese and avocado, often topped with crisp pork.",
    tip: "Ecuador uses the US dollar, but small vendors hate big bills — keep coins and ones for buses, markets and taxis.",
    dont: "Don't wander the old town or El Panecillo alone after dark; muggings happen, so take a registered taxi or rideshare.",
    bestTime: "June to September dry season; sitting on the equator, Quito has spring-like temperatures all year.",
    phrase: "¿Qué fue? (keh fweh) — What's up? / common Ecuadorian greeting.",
    pacing: "2-3 days",
    headsup: "At 2,850 m you may feel the altitude; the Mitad del Mundo equator monument sits a short drive north of the centre."
  },
  {
    id: "amazon-rainforest-expedition",
    name: "Amazon rainforest expedition",
    region: "South America",
    country: "Brazil",
    type: "Natural",
    weekends: 2,
    costUSD: 2400,
    lat: -3.47,
    lng: -62.22,
    blurb: "Pink dolphins surface, howler monkeys roar, and the river runs to the horizon through endless green.",
    wiki: "https://en.wikipedia.org/wiki/Amazon_rainforest",
    splurge: false,
    badge: null,
    eat: "Tacacá — a tangy Amazonian soup of jambu leaves (that tingle your lips), dried shrimp and tucupi broth.",
    tip: "Choose a lodge deep from Manaus and go on dawn and night canoe outings — wildlife shows at the river's edges, not midday.",
    dont: "Don't buy souvenirs made from animal teeth, feathers or skins; the trade is illegal and fuels poaching.",
    bestTime: "High-water season (May to July) for canoe access into flooded forest; low water (September to November) for beaches and fishing.",
    phrase: "Obrigado (oh-bree-GAH-doo) — Thank you / 'obrigada' if you're a woman.",
    pacing: "5-7 days",
    headsup: "You'll need yellow-fever vaccination and malaria precautions; pack quick-dry clothes, a headlamp, and strong insect repellent."
  },
  {
    id: "torres-del-paine-w-trek",
    name: "Torres del Paine — the W trek",
    region: "South America",
    country: "Chile",
    type: "Trek",
    weekends: 2,
    costUSD: 1800,
    lat: -51.00,
    lng: -73.00,
    blurb: "Granite towers, hanging glaciers and turquoise lakes unfold over four days of wind-scoured Patagonian trail.",
    wiki: "https://en.wikipedia.org/wiki/Torres_del_Paine_National_Park",
    splurge: false,
    badge: null,
    eat: "Cordero al palo — whole lamb splayed and slow-roasted over open fire, the Patagonian shepherd's feast.",
    tip: "Book refugios or campsites months ahead through Vertice and Las Torres — you cannot sleep on the trail without a reservation.",
    dont: "Don't use camp stoves outside designated areas or stray off-trail; past fires have scarred the park and rules are strict.",
    bestTime: "December to February austral summer for long days and open refugios; shoulder months mean fewer crowds, fiercer wind.",
    phrase: "Buena onda (BWEH-nah OWN-dah) — Good vibes / cheerful Chilean expression.",
    pacing: "4-5 days on the W",
    headsup: "Patagonian weather flips through four seasons in an hour, with gusts over 100 km/h — pack real waterproofs and windproof layers."
  },
  {
    id: "patagonia-perito-moreno-el-chalten",
    name: "Patagonia — Perito Moreno & El Chaltén",
    region: "South America",
    country: "Argentina",
    type: "Natural",
    weekends: 2,
    costUSD: 1800,
    lat: -49.33,
    lng: -73.04,
    blurb: "A living glacier calves blue ice into a lake while Fitz Roy's jagged spires draw every hiker north.",
    wiki: "https://en.wikipedia.org/wiki/Perito_Moreno_Glacier",
    splurge: false,
    badge: null,
    eat: "Calafate berry — tart Patagonian fruit in jam or ice cream; legend says eating it ensures you return.",
    tip: "Base in El Calafate for the glacier and El Chaltén (Argentina's trekking capital) for free day hikes to Laguna de los Tres.",
    dont: "Don't stand at the glacier viewing rails outside marked zones — calving ice has killed onlookers struck by waves and debris.",
    bestTime: "November to March for trekking; the glacier's dramatic ice-bridge ruptures happen unpredictably every few years.",
    phrase: "Dale (DAH-leh) — Okay / sure / let's go, the all-purpose Argentine yes.",
    pacing: "5-6 days",
    headsup: "El Chaltén has limited ATMs that often run dry — bring enough pesos in cash before you arrive in town."
  },
  {
    id: "galapagos-cruise",
    name: "Galápagos cruise",
    region: "South America",
    country: "Ecuador",
    type: "Island",
    weekends: 3,
    costUSD: 7700,
    lat: -0.78,
    lng: -90.31,
    blurb: "Giant tortoises, blue-footed boobies and snorkeling sea lions ignore you on islands evolution made famous.",
    wiki: "https://en.wikipedia.org/wiki/Gal%C3%A1pagos_Islands",
    splurge: true,
    badge: null,
    eat: "Encebollado — hearty Ecuadorian fish soup with tuna, yuca and pickled red onion, the classic island breakfast.",
    tip: "Pick a small live-aboard boat over day trips to reach the remote outer islands; always stay on marked trails behind your naturalist guide.",
    dont: "Don't touch the wildlife or use flash photography, and keep two metres back — animals are fearless but legally protected.",
    bestTime: "Year-round; December to May is warmer with calm seas, June to November cooler with richer marine life and whales.",
    phrase: "¡Qué chévere! (keh CHEH-veh-reh) — How cool! / favourite Ecuadorian exclamation.",
    pacing: "7-10 days",
    headsup: "On arrival you pay a national-park entry fee plus a transit card, and quarantine rules ban bringing seeds, food or fruit ashore."
  }
];
